### ISSUE TITLE
複数のtypo

### ISSUE THREAD

**Issue by voidproc** [Siv3D/OpenSiv3D#1016]
以下の typo を見つけたので報告します。
GitHub の検索機能でヒットしたものを列挙しています。
プルリクエストを出す際、1つのコミットにまとめてしまっていいでしょうか。

resrve → reserve
- [Siv3D/include/Siv3D/Blob.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/Blob.hpp)
- [Siv3D/src/Siv3D/Blob/SivBlob.cpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/src/Siv3D/Blob/SivBlob.cpp)
- [Siv3D/include/Siv3D/MemoryWriter.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/MemoryWriter.hpp)
- [Siv3D/src/Siv3D/MemoryWriter/SivMemoryWriter.cpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/src/Siv3D/MemoryWriter/SivMemoryWriter.cpp)

rematk → remark
- [Siv3D/include/Siv3D/FontMethod.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/FontMethod.hpp)

Fitrst → First
- [Siv3D/include/Siv3D/Formatter.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/Formatter.hpp)
- [Siv3D/include/Siv3D/detail/Formatter.ipp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/detail/Formatter.ipp)

Requied → Required
- [Siv3D/include/Siv3D/HTTPStatusCode.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/HTTPStatusCode.hpp)

Fromat → Format
- [Siv3D/include/Siv3D/Image.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/Image.hpp)
- [Siv3D/include/Siv3D/ImageFormat/PPMEncoder.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/ImageFormat/PPMEncoder.hpp)
- [Siv3D/src/Siv3D/ImageFormat/PPM/PPMEncoder.cpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/src/Siv3D/ImageFormat/PPM/PPMEncoder.cpp)

Dpeth → Depth
- [Siv3D/include/Siv3D/RenderTexture.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/RenderTexture.hpp)
- [Siv3D/src/Siv3D/RenderTexture/SivRenderTexture.cpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/src/Siv3D/RenderTexture/SivRenderTexture.cpp)

**Comment by Reputeless** [comment]
Good catch!
はい。まとめていただいて大丈夫です。
