### ISSUE TITLE
OTF 形式のフォントを使用して PolygonGlyph 化しようとすると正しい結果が得られない

### ISSUE THREAD

**Issue by Ryoga-exe** [Siv3D/OpenSiv3D#1019]
**予期しない動作の内容 | Describe the unexpected behavior**

サンプル集にある [2D 物理演算の Text to Polygon](https://zenn.dev/reputeless/books/siv3d-documentation/viewer/sample-2d-physics#text-to-polygon) のフォントを変更してみたところ、OTF 形式のフォントを読み込んだ場合に正しく PolygonGlyph 化できずに描画されます。TTF や WOFF 形式のフォントでは問題なく描画されました。

いくつかのフォントで確認しました。以下にそのうちの 2 つの様子を載せます。
使用したフォントは順に https://typingart.net/ からダウンロードできる、[はんなり明朝](https://typingart.net/?p=44) と [Typingart Grotesque](https://typingart.net/?p=486) です。

![Animation1](https://github.com/Siv3D/OpenSiv3D/assets/49950206/d89d6b7e-76cb-4add-9cae-91345444b52a)
![Animation2](https://github.com/Siv3D/OpenSiv3D/assets/49950206/9c1d369b-6ad2-4463-afc1-0a7f5e7a7151)

このように穴の部分が変換されるような挙動になります。

**再現方法 | To Reproduce**

サンプル集にある [2D 物理演算の Text to Polygon](https://zenn.dev/reputeless/books/siv3d-documentation/viewer/sample-2d-physics#text-to-polygon) の `const Font font{ 100, Typeface::Bold };` の箇所を `const Font font{ 100, U"font.otf"};` のように OTF 形式のフォントを指定すると再現できるかと思います。

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 11 (22H2)
 - バージョン | Version: OpenSiv3D v0.6.10
 - GPU: AMD Radeon Graphics

**備考 | Additional context**

**Comment by Reputeless** [comment]
ご報告ありがとうございます。調査します。

**Comment by Raclamusi** [comment]
フォントのデータ形式には、時計回りを塗りつぶしとするものと、反時計回りを塗りつぶしとするものがあります。
Siv3D では時計回りが塗りつぶしであることを前提として実装されているのに対し、問題が発生するフォントは反時計回りを塗りつぶしとしているため、輪郭と穴が逆転してこの問題が発生します。

Siv3D で使用しているライブラリの FreeType には塗りつぶしとする回転方向を調べる API が用意されているので、その結果を考慮して適切に処理することでこの問題は解決できます。

https://freetype.org/freetype2/docs/reference/ft2-outline_processing.html#ft_outline_get_orientation

**Comment by Raclamusi** [comment]
調べたついでに pull request 投げました。

**Comment by Reputeless** [comment]
おー、この API の存在は知りませんでした。
PR ありがとうございます。v0.6.11 に取り入れます。

**Comment by Reputeless** [comment]
開発中の v0.6.11 に @Raclamusi さんの #1027 をマージしました。
報告・実装ありがとうございました！
