### ISSUE TITLE
ランタイムエラーを踏んだとき、Web ブラウザを起動して解決法のページに飛ばす機能の改善案

### ISSUE THREAD

**Issue by engineer-fumi** [Siv3D/OpenSiv3D#1034]
**追加する機能の内容 | Describe the solution you'd like**

ランタイムエラーを踏んだとき、Web ブラウザを起動して解決法のページに飛ばす機能について、メッセージおよびボタンが以下のようになってると分かりやすいかもしれないと思いました。『』はボタンです。‬

‪トラブルシューティング(GitHubページのURL)を開きますか？それとも本メッセージを閉じますか？‬

‪『開く』『閉じる』‬

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**

現状だと、以下のように思いました。‬採用して頂くことで、ユーザビリティの向上されるかと思われます。

‪・トラブルシューティングがGitHub上のページのことだと思えない‬
‪・閉じるボタンで開かないことは想定できない‬

**備考 | Additional context**

**Comment by Reputeless** [comment]
- https://twitter.com/Reputeless/status/1686765818737250304

![image](https://github.com/Siv3D/OpenSiv3D/assets/3108136/f3fa0193-08f8-4373-9971-7a943263b01c)

![image](https://github.com/Siv3D/OpenSiv3D/assets/3108136/32c63c8c-9b19-4488-b08a-8e1b2e7e681e)

トラブルシューティング機能の目的は、Siv3D を誤用しているプログラマに資料を読んでもらい、迅速に問題を解決してもらうことです。
基本的には「無視されないようにする意図」があり、熟練者が誤ってメッセージボックスを出した場合は (x) で閉じればよいため、目的に適ったデザインになっていると思います。ユーザが目にするのも一生で 1 回か 2 回でしょう。

メッセージボックスの本文からは、「OK を押すと何らかの Web ページが開くこと」「見たくない場合は OK を押さなければよいこと」が十分に読み取れると考えていますが、次の変更を加えることにします。

```diff
- U"[OK] を押すとトラブルシューティングのページを開きます。"
+ U"[OK] を押すと Web ブラウザでトラブルシューティングのページを開きます。"
```
