### ISSUE TITLE
Rect, RectF から角度を指定して平行四辺形を作る関数

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#1056]
- reported by: https://discord.com/channels/443310697397354506/999983621408567326/1141388294882611260

**Comment by yama-can** [comment]
実装します！

**Comment by Reputeless** [comment]
pull request をする前に、メンバ関数名と実装案（コード）をこちらのコメントで書いて、僕から OK を得てください。

**Comment by yama-can** [comment]
わかりました。メンバ関数名として「ずらされた」の意味をもつ"shift"に"shearedX"や"shearedY"と同じくXとYをつけたものはどうでしょうか

**Comment by yama-can** [comment]
実装は
```cpp
inline constexpr Quad Rect::shiftX(const double angle) const noexcept 
{
	return shearedX(tan(angle) * h / 2);
}

inline constexpr Quad Rect::shiftY(const double angle) const noexcept
{
	return shearedY(tan(angle) * w / 2);
}
```
でできました。

**Comment by Reputeless** [comment]
ありがとうございます。既存のメンバ関数を利用してコードを短くした良い実装だと思います。
下記の点について対応してください。

- C++ 標準ライブラリの関数は `std::` 修飾を付けてください
- 数学関数 `std::tan()` は C++20 時点では constexpr ではないため、`constexpr` を外してください
- 自身を変更しないメンバ関数名は、他のメンバ関数にならい（～ed と受動態にしてください。例: `.rotated()`, `.rounded()`）
- shift は CG の文脈では平行移動を連想するため、skew が良いと思います
  - 例: https://learn.microsoft.com/ja-jp/dotnet/desktop/wpf/graphics-multimedia/how-to-skew-an-element?view=netframeworkdesktop-4.8
- (pull request 時には）`Rect` だけでなく `RectF` にも実装してください
  - メンバ関数の宣言場所は `shearedY()` の直後が良いと思います

**Comment by yama-can** [comment]
わかりました。ご指摘いただいた条件に沿って実装が完了したらPull Requestを送ります。
