### ISSUE TITLE
const な値を返すメンバ関数の指摘

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#1065]
戻り値の型が const な値であるメンバ関数が、JSON.hpp 以外に2つ見つかりました。

- `Shape2D::indices() const`
- `SceneManager::get() const`

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/Shape2D.hpp?ts=4#L184-L187

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/SceneManager.hpp?ts=4#L187-L190

`Shape2D::indices() const` の戻り値の型については、おそらく `const Array<TriangleIndex>&` の誤り（ `&` の付け忘れ）です。

`SceneManager::get() const` の戻り値の型については、`std::shared_ptr<const Data>` の誤りであることと、`const std::shared_ptr<Data>&` の誤りであることが考えられます。
おそらく前者だと思いますが、Siv3D では後者のようにしている例もあります（以下参照）。

**`std::shared_ptr<const T>` を返す例**

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/Serialization.hpp?ts=4#L73-L74

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/Serialization.hpp?ts=4#L98-L99

**`const std::shared_ptr<T>&` を返す例**

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/Physics2D/P2Body.hpp?ts=4#L384-L388

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/include/Siv3D/Script.hpp?ts=4#L99

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
ご指摘の通り `Shape2D::indices()` の戻り値は `const Array<TriangleIndex>&` が正です。
`SceneManager` については `const` が余分で `std::shared_ptr<const Data>` が正です。
pull request を作成していただけますか。

`P2Body` と `Script` についても再検討が必要な気がしますが、重要度は低いので v0.8 に先送りします。
