### ISSUE TITLE
Shape2Dの当たり判定の実装

### ISSUE THREAD

**Issue by yama-can** [Siv3D/OpenSiv3D#1067]
**追加する機能の内容 | Describe the solution you'd like**
Shape2Dに当たり判定を実装したい

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
Polygonに変換する必要がなくなる

**備考 | Additional context**

**Comment by Reputeless** [comment]
Shape2D は Polygon からあたり判定等を省いて描画に専念させることで、余分なオーバーヘッドを削減したクラスです。今後も Shape2D があたり判定を持つことはありません。1 度だけ Polygon に変換し、それを使い回してあたり判定で用いてください。
