### ISSUE TITLE
Polygon::scale() の性能改善

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#1069]
`Polygon::scale()` などの呼び出しのたびに `detail::CalculateBoundingRect()` でバウンディングボックスを計算し直すのは無駄が多いです。
この場合、バウンディングボックスをポリゴンと同様に拡大・縮小するだけで十分です。

**変更箇所**

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp?ts=4#L458-L459

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp?ts=4#L497-L498

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp?ts=4#L537-L538

https://github.com/Siv3D/OpenSiv3D/blob/18396875c616208348457378827bc011d126cc7a/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp?ts=4#L577-L578

**変更内容**

```diff
--- a/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp
+++ b/Siv3D/src/Siv3D/Polygon/PolygonDetail.cpp
@@ -455,8 +455,7 @@ namespace s3d
			point *= sf;
		}
 
-		// [Siv3D ToDo] 不要に
-		m_boundingRect = detail::CalculateBoundingRect(m_vertices.data(), m_vertices.size());
+		m_boundingRect = m_boundingRect.scaledAt(Vec2{ 0, 0 }, s);
	}
 
	void Polygon::PolygonDetail::scale(const Vec2 s)
@@ -494,8 +493,7 @@ namespace s3d
			point *= sf;
		}
 
-		// [Siv3D ToDo] 不要に
-		m_boundingRect = detail::CalculateBoundingRect(m_vertices.data(), m_vertices.size());
+		m_boundingRect = m_boundingRect.scaledAt(Vec2{ 0, 0 }, s);
	}
 
	void Polygon::PolygonDetail::scaleAt(const Vec2 pos, const double s)
@@ -534,8 +532,7 @@ namespace s3d
			point = (posF + (point - posF) * sf);
		}
 
-		// [Siv3D ToDo] 不要に
-		m_boundingRect = detail::CalculateBoundingRect(m_vertices.data(), m_vertices.size());
+		m_boundingRect = m_boundingRect.scaledAt(pos, s);
	}
 
	void Polygon::PolygonDetail::scaleAt(const Vec2 pos, const Vec2 s)
@@ -574,8 +571,7 @@ namespace s3d
			point = (posF + (point - posF) * sf);
		}
 
-		// [Siv3D ToDo] 不要に
-		m_boundingRect = detail::CalculateBoundingRect(m_vertices.data(), m_vertices.size());
+		m_boundingRect = m_boundingRect.scaledAt(pos, s);
	}
 
	double Polygon::PolygonDetail::area() const noexcept
```

**Comment by Reputeless** [comment]
良さそうです。v0.6.13 で採用したいと思います。
pull request を作成していただければマージします。私に任せたい場合はお知らせください。

**Comment by Raclamusi** [comment]
今さら気づいたんですが、`Polygon` の各点の座標は `float` で扱っているのに対し、`m_boundingRect` は `double` で扱っているので、この方法だと今までと精度が変わります。
大丈夫ですか？

```c++
# include <Siv3D.hpp> // Siv3D v0.6.12

void Main()
{
	constexpr double Scale = 1.1;

	const auto polygon = Image{ U"example/siv3d-kun.png" }.alphaToPolygonCentered(1).simplified(4);

	// 従来手法
	const auto rect1 = polygon.scaled(Scale).boundingRect();

	// 提案手法
	const auto rect2 = polygon.boundingRect().scaledAt(Vec2{0, 0}, Scale);
	
	Print << U"従来手法: {}"_fmt(rect1);
	Print << U"提案手法: {}"_fmt(rect2);
	Print << U"従来手法の結果と提案手法の結果は一致{}"_fmt((rect1 == rect2) ? U"する" : U"しない");

	while (System::Update())
	{

	}
}
```

**出力**
```
従来手法: (-181.5, -260.70001220703125, 362.4499969482422, 520.8500061035156)
提案手法: (-181.50000000000003, -260.70000000000005, 362.45000000000005, 520.85)
従来手法の結果と提案手法の結果は一致しない
```

**Comment by Reputeless** [comment]
よく考えると `scale` 系の関数で `detail::CalculateBoundingRect()` の入力が `m_vertices` なのは 2 つの点で不適切ですね。

- 穴の頂点も考慮することになりコストが余分になる
- `Float2` 化された頂点なので `Polygon` 作成時の `Vec2` 座標よりも精度が落ちる

従来手法が問題ありで、今回の提案でそれが改善されます。
同様の誤りを防ぐため、合わせて `CalculateBoundingRect()` 関数を `const Vec2*` を引数にとる非テンプレート関数にすると良さそうです。

**Comment by Raclamusi** [comment]
わかりました。
それも含めて pull request を作成します。
