### ISSUE TITLE
MSDF と FontStyle::Bold (BoldItalic) を両指定したフォントの描画が崩れる

### ISSUE THREAD

**Issue by voidproc** [Siv3D/OpenSiv3D#1082]
**予期しない動作の内容 | Describe the unexpected behavior**
MSDF と FontStyle::Bold (or BoldItalic) を組み合わせたフォントを描画するとき、文字によっては表示が崩れます。
SDF に関しても同様と思います。

**再現方法 | To Reproduce**
次のコードにより再現
```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6.11

void Main()
{
    Scene::SetBackground(ColorF{ 0 });
    FontAsset::Register(U"Regular_Default",    FontMethod::MSDF, 64, Typeface::Regular, FontStyle::Default);    // OK
    FontAsset::Register(U"Regular_Bold",       FontMethod::MSDF, 64, Typeface::Regular, FontStyle::Bold);       // 崩れる
    FontAsset::Register(U"Regular_BoldItalic", FontMethod::MSDF, 64, Typeface::Regular, FontStyle::BoldItalic); // 崩れる

    while (System::Update())
    {
        constexpr auto text = U"えさちぬぱピプぽ本漢字"_sv;
        FontAsset(U"Regular_Default")(text).draw(Vec2{ 20, 50 });
        FontAsset(U"Regular_Bold")(text).draw(Vec2{ 20, 150 });
        FontAsset(U"Regular_BoldItalic")(text).draw(Vec2{ 20, 250 });
    }
}
```

実行結果:
![スクリーンショット 2023-09-02 143749](https://github.com/Siv3D/OpenSiv3D/assets/17496857/c68cc8c0-eb3a-4d16-b17e-76671e558a87)

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
- OS: Windows 11
- バージョン | Version: 22H2
- GPU: Intel Iris Xe Graphics
- OpenSiv3D 0.6.11

**Comment by Reputeless** [comment]
v0.6.12 で開発中の #1095 の過程で大幅に改善できました。
よく見るとわずかにノイズはありますが（プの〇と漢の大）、とりあえずこれでいきます。
ご報告ありがとうございました。

![20230918-195552-630](https://github.com/Siv3D/OpenSiv3D/assets/3108136/0c9e146c-bd23-431b-a9a6-eba9bf342d66)
