### ISSUE TITLE
キーを押していないのにpressed()がtrueを返す状況がある

### ISSUE THREAD

**Issue by yama-can** [Siv3D/OpenSiv3D#1083]
## 再現方法
1. マウスカーソルをウィンドウの外に置く
2. 任意のキーを押す
3. キーを押したまま、別のウィンドウをアクティブにする
4. キーを離す
5. マウスカーソルがウィンドウに触れないように、アクティブにしたウィンドウを閉じる
6. キーのpressed()がtrueを返している
7. マウスカーソルをウィンドウに乗せると、pressed()がtrueを返すのを止める

[報告元](https://canary.discord.com/channels/443310697397354506/1000291580915232879/1147843053999095808)

**Comment by yama-can** [comment]
しっかり`CKeyboard.cpp`のGetKeyboardStateのアップデートなどは行われています。

**Comment by Reputeless** [comment]
Issue 立てありがとうございます。調査します。

**Comment by yama-can** [comment]
お願いします。

**Comment by voidproc** [comment]
[GetKeyState 関数のドキュメント](https://learn.microsoft.com/ja-jp/windows/win32/api/winuser/nf-winuser-getkeystate) によると、

> スレッドがメッセージ キューからキー メッセージを読み取る際に、この関数から返されるキーの状態が変わります。

とあるので（GetKeyboardState 関数も同様と思います）、Siv3D のウィンドウがバックグラウンドになるとキーメッセージを受け取れなくなり、状態が変わらなくなるのだと思います。また、マウスが触れると WM_MOUSEMOVE メッセージが送られてくるので、これを読み取ることで状態が変わるのかなと。

試しに以下のコードで、一定時間ごとに適当なキーメッセージを自分のウィンドウに送信することで、強制的に状態を更新できることを確認しました。

```
# include <Siv3D.hpp> // OpenSiv3D v0.6.11
#include <Siv3D/Windows/Windows.hpp>

void Main()
{
	Scene::SetBackground(ColorF{ 0 });

	Timer timer{ 1s, StartImmediately::Yes };

	while (System::Update())
	{
		if (timer.reachedZero())
		{
			timer.restart();

			::PostMessage((HWND)Platform::Windows::Window::GetHWND(), WM_KEYDOWN, 0x07, 0);
		}

		PutText(Format(KeyA.pressed()), Scene::CenterF());
	}
}
```

ウィンドウメッセージによらずキーボードの状態を取得できる関数として GetAsyncKeyState 関数がありますが、これは GetKeyboardState のように一気に複数のキーの状態を取得することはできないようです。

https://learn.microsoft.com/ja-jp/windows/win32/api/winuser/nf-winuser-getasynckeystate

**Comment by Reputeless** [comment]
@voidproc 調査ありがとうございます。原因の究明が捗りました。
ご提案手法は work-around として有効です。
一方 Siv3D 内部で下記部分でウィンドウのフォーカスの有無を追加の条件にすることで、根本から解決できそうです。
v0.6.12 では後者で対応したいと思います。

https://github.com/Siv3D/OpenSiv3D/blob/3c60352fc7db4a94cf81d471129782e0fe5c3b7a/Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Keyboard/CKeyboard.cpp#L123
