### ISSUE TITLE
Image::clipped() の性能改善

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#1087]
`Image::clipped()` について、実行速度が従来の実装の約2倍、場合によっては約4倍に向上する実装を提案します。

### 提案手法の概要

従来の `Image::clipped()` の実装は、愚直なループにより新たな領域に切り取り領域を1画素ずつコピーするものです。
提案する手法では、行ごとに `std::memcpy()` を用いてコピーすることにより効率的に処理させます。
また、rvalue からの呼び出しであるときは、`std::memmove()` を用いた in-place な実装によりさらに効率的に処理させます。
ただし、出力画像のピクセル数が `m_data.capacity()` を超えるときは却って非効率になるため、in-place でない実装に切り替えます。

### 提案手法の実装と測定用コード

提案手法の実装と測定用コードを以下の gist に示します。
このコード内の `my::clipped()` が提案手法を実装したものです。

https://gist.github.com/Raclamusi/a0dabb15a70e7c715c4a49511a8dbbae?ts=4

### 測定結果

従来手法と提案手法それぞれの出力画像のピクセル数と実行時間の関係を以下のグラフに示します。

![出力画像のピクセル数を横軸、実行時間を縦軸としたグラフ](https://github.com/Siv3D/OpenSiv3D/assets/61970673/8a7a0c6f-2763-4979-b7d6-d099fd410efb)

lvalue 向けの実装の実行時間は、従来の1/2程度に向上しました。
rvalue 向けの実装の実行時間は、出力画像のピクセル数が元の画像のピクセル数より小さいときは従来の1/4程度に向上し、切り取り領域が元の画像の領域と一致するときはほぼ0に、出力画像のピクセル数が元の画像のピクセル数を超えるときは lvalue 向けの実装に委譲されて同様に従来の1/2程度になりました。

### 計測環境

|項目|環境|
|---|---|
|プロセッサ|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz|
|RAM|8.00 GB|
|OS|Windows 11 Home 22H2|
|IDE|Microsoft Visual Studio Community 2022 (64 ビット) 17.7.3|
|ビルド|Release x64|

**Comment by Reputeless** [comment]
ありがとうございます！
改善したいと思ってました。確認します。

**Comment by Reputeless** [comment]
良さそうです。プルリクエストお願いします。
`int32(0)` は `0` と書いて良いです。
