### ISSUE TITLE
Rect の一部の constepr メンバ関数が非アクティブな共用体を使用している

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#1118]
- reported by: https://discord.com/channels/443310697397354506/1000291580915232879/1164766194906173470 
- 他のクラスも調査する

**Comment by Raclamusi** [comment]
「他のクラスも調査する」は別の issue でやる感じですか？

**Comment by Reputeless** [comment]
はい。ほかのクラスに該当例が見つかったら Issue を立ててください。
