### ISSUE TITLE
Multiplayer_Photon で joinRoomReturn が呼ばれない

### ISSUE THREAD

**Issue by nokotan** [Siv3D/OpenSiv3D#1169]
**予期しない動作の内容 | Describe the unexpected behavior**

class Multiplayer_Photon を継承したクラスで、部屋に参加した時のコールバック関数である joinRoomReturn を定義しても、この間数が呼ばれることがない。

**再現方法 | To Reproduce**

https://zenn.dev/reputeless/scraps/03d951dddb53ab の手順に加え、次の関数を定義する

```cpp
void joinRoomReturn(LocalPlayerID localPlayerID, int32 errorCode, const String& errorString) override
{
}
```

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows11
 - バージョン | Version:
 - GPU:
 - ブラウザ (Web 版) | Browser:

**発生環境(モバイルの場合) | Smartphone (please complete the following information):**
 - デバイス | Device:
 - OS:
 - バージョン | Version:
 - ブラウザ (Web 版) | Browser:

**備考 | Additional context**

おそらく class Multiplayer_Photon::PhotonDetail の joinRoomReturn 実装漏れが原因

**Comment by Reputeless** [comment]
ご報告ありがとうございます。開発中の v0.6.14 で修正完了しました。
