### ISSUE TITLE
v0.6.14 での JSON の挙動の問題

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#1192]
- reported by: https://twitter.com/sfpgmr/status/1748650012857487426?t=i09PYczGapfZAMpcmjmKSw&s=19

**Comment by Raclamusi** [comment]
#1165 で `JSON::operator =(const JSON&)` の挙動を `m_detail->get()` の代入から `m_detail` の代入に変更したので、参照を持つ `JSON` オブジェクトに対して `JSON::operator =(const JSON&)` を使うと参照のすげ替えが起こり、要素の値を `JSON` オブジェクトで書き換えることができなくなっています（ `std::reference_wrapper::operator=` みたいな挙動になっています）。

ツイートのコードでは、`destJson[U"array"] = srcJson2;` の行でその問題が発生しています。

`JSON::operator =(const JSON&)` は `m_detail->get()` をコピーする実装のほうがよさそうです。
