### ISSUE TITLE
Dialog::SaveFileのデフォルトファイル名を指定したい

### ISSUE THREAD

**Issue by tyanmahou** [Siv3D/OpenSiv3D#1199]
**追加する機能の内容 | Describe the solution you'd like**

`Dialog::SaveFile`でファイル保存のダイアログを表示できますが、その際のデフォルトで入力されているファイル名を指定できるようにしたい

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
ファイル保存のダイアログのファイル名が空の状態で開かれるのでアプリケーション使用者は全て入力しないといけません。
保存するファイルのファイル名を変えられる融通は持たせつつも、特にこだわりがない人向けに自動でファイル名が設定されていると嬉しいケースがあります。

**備考 | Additional context**

**Comment by Reputeless** [comment]
ご提案ありがとうございました。
Siv3D v0.6.15 で `Dialog::SaveFile()` に第 4 引数を追加し、デフォルトのファイル名を指定できるようにしました。
