### ISSUE TITLE
BMP サポートの強化（1-bit, 4-bit, 16-bit, 特殊なヘッダやパレットのロード）

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#1204]
- reported by: https://twitter.com/raclamusi/status/1758153052765495783?t=4ToByV_uslHfaD724ohQQg&s=19

**Comment by Reputeless** [comment]
1. では対応しましょう。テスト用に各フォーマットの bmp ファイルを用意してください（コミットには含まず）。
2. `std::bad_alloc` を使うようにして大丈夫です。

**Comment by Raclamusi** [comment]
ヘッダと画像データの間にギャップがあるとき、および、パレットの色数が最大でないときに正しく読み込めないバグがありました。
一緒に直します。

![スクリーンショット](https://github.com/Siv3D/OpenSiv3D/assets/61970673/e8616101-9e04-4fdd-ab9d-9a6542206935)

**Comment by Raclamusi** [comment]
テスト用ソースコード： https://gist.github.com/Raclamusi/039af3aa2698424a3bfc48e885224f94
テスト用画像ファイル： https://drive.google.com/drive/folders/1UFL-rqHZ3wjn-5efr_9ghWNtZ-GqYlOD?usp=sharing

**Comment by Raclamusi** [comment]
テスト用コード、実装完了しました。

![ソースコード](https://github.com/Siv3D/OpenSiv3D/assets/61970673/d1254c05-9924-489d-afc0-32dbc14971b6)

**Comment by Raclamusi** [comment]
PR #1207 のコメントに変更についての詳しい説明を書きました。
