### ISSUE TITLE
Image::inBounds

### ISSUE THREAD

**Issue by comefrombottom** [Siv3D/OpenSiv3D#1229]
**追加する機能の内容 | Describe the solution you'd like**
Grid::inBounds()に相当するものをImageにも
**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
Gridとの一貫性
**備考 | Additional context**

**Comment by Reputeless** [comment]
開発中の v0.6.15 に実装しました。ご提案ありがとうございました。
