### ISSUE TITLE
Linux版のDockerビルド環境構築

### ISSUE THREAD

**Issue by sthairno** [Siv3D/OpenSiv3D#1252]
**追加する機能の内容 | Describe the solution you'd like**

現在GitHub Actionsで動作しているLinuxのテスト環境をDockerに置き換える

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**

- ビルドの問題
  - コンテナで確実に動作する環境が用意できるため、Linux版ユーザーの間で多く見られるコンパイル時のトラブルを減らせる
  - [Docker Hub](https://www.docker.com/ja-jp/products/docker-hub/)との連携でビルド済みバイナリを配布でき、ユーザーが1からコンパイルする手間を省ける
- 開発環境の問題
  - Ubuntu以外のディストリビューションでも開発環境の構築が簡単になる   
    参考：[Build on Fedora (Siv3D Discord チャンネル)](https://discord.com/channels/443310697397354506/1222181562666450985)
  - Windows/MacでもDocker Desktopを用いてLinux版の開発ができるようになる

**備考 | Additional context**

試しにDockerでOpenSiv3Dのコンパイルができるところまで実装しました。

https://github.com/sthairno/OpenSiv3D/commit/7553d95a8067715da3577e24433d041fa999fd62

**Comment by Reputeless** [comment]
Sounds cool!
いろいろ聞きたいことがあるので、オンラインで相談させてください。

**Comment by sthairno** [comment]
Close理由
- いくつかのビルド問題は解消できるが、開発の取り掛かりやすさが解消できない
  - SDKをインストールしたらすぐにソースコードを実行して試せる状態が理想

要調査 📝
- FlatpakなどのGUIに対応した抽象化レイヤーを使う方法
- 各ディストリビューションごとにインストーラーを作る方法
  - 単純にテスト対象が広がるのでメンテの手間が増える
    - 依存ライブラリのバージョン管理とか
  - Vagrantで簡単にテスト用の仮想マシンを作れるようにする？
    https://dev.classmethod.jp/articles/virtual-box-vagrant/
  - Gtk or Qtを使えばいくらかの差分を吸収してくれそう
    - IME実装もこれがあると便利になる✨

**Comment by Reputeless** [comment]
まとめ、ありがとうございます。
