### ISSUE TITLE
BinaryReader::lookahead() のバグ

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#1265]
## 読み込み位置が変わる可能性がある

`setPos(previousPos)` しないまま返るコードパスがあります。
読み込みに失敗したとき（ `return 0;` の前）にも書き込み位置を戻すべきかどうかは、 `IReader::lookahead()` の失敗時の仕様が見つからないのでわかりません。

https://github.com/Siv3D/OpenSiv3D/blob/9c77228c3f1642b1274f10be8a86379d37a0cfe1/Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/BinaryReader/BinaryReaderDetail.cpp#L249-L257

https://github.com/Siv3D/OpenSiv3D/blob/9c77228c3f1642b1274f10be8a86379d37a0cfe1/Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/BinaryReader/BinaryReaderDetail.cpp#L289-L297

https://github.com/Siv3D/OpenSiv3D/blob/9c77228c3f1642b1274f10be8a86379d37a0cfe1/Siv3D/src/Siv3D-Platform/macOS_Linux/Siv3D/BinaryReader/BinaryReaderDetail.cpp#L164-L172

https://github.com/Siv3D/OpenSiv3D/blob/9c77228c3f1642b1274f10be8a86379d37a0cfe1/Siv3D/src/Siv3D-Platform/macOS_Linux/Siv3D/BinaryReader/BinaryReaderDetail.cpp#L195-L203

**Comment by Reputeless** [comment]
ご報告ありがとうございました。修正しました。
私では思いつかなかったのですが、意図的に
`if (not m_file.file.read`
で失敗する状況を作れる方法があれば、今後（siv8 など）のテストに追加します。
