### ISSUE TITLE
MemoryWriter::write() のバグ

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#1266]
## 書き込み位置より後ろの内容が消える

`newSize` が元の `m_blob.size()` より小さいときもリサイズされ、このとき書き込み位置より後ろにあった内容は消えてしまいます。
この挙動は `BinaryWriter` と一貫性がなく、おそらく誤った挙動です。

```cpp
{
	BinaryWriter writer{ U"test.txt" };
	writer.write("Hello, World!", 13);
	writer.setPos(7);
	writer.write("C++!", 4);
	// "Hello, C++!d!"
}
{
	MemoryWriter writer;
	writer.write("Hello, World!", 13);
	writer.setPos(7);
	writer.write("C++!", 4);
	// "Hello, C++!"
}
```

https://github.com/Siv3D/OpenSiv3D/blob/9c77228c3f1642b1274f10be8a86379d37a0cfe1/Siv3D/src/Siv3D/MemoryWriter/SivMemoryWriter.cpp#L67-L74

## バッファオーバーフローの危険

引数 `sizeBytes` が非負かどうかがチェックされておらず、範囲外の領域に書き込む可能性があります。

**Comment by Reputeless** [comment]
ご報告ありがとうございました。重大なバグでした。
開発中の v0.6.16 で修正しました。
