### ISSUE TITLE
GUIで表示/非表示の有無を調べる

### ISSUE THREAD

**Issue by GRGSIBERIA** [Siv3D/OpenSiv3D#160]
`GUI::isVisible()`もしくは`GUI::isEnable()`のように，GUIが有効/表示の有無を調べる関数が欲しいです．
現在，GUIを開発していないみたいですが，将来的にGUIを実装するときにはぜひ．

**Comment by Reputeless** [comment]
現行版でも
```cpp
gui.style.visible;
gui.style.active;
```
で取得可能です。OpenSiv3D でもこれを引き継いで実装します。
