### ISSUE TITLE
Array::in_groups()の動作について

### ISSUE THREAD

**Issue by para7** [Siv3D/OpenSiv3D#189]
#include <Siv3D.hpp>

void Main()
{
	Array<int> ar;
	for (int i : step(6))
	{
		ar.push_back(i);
	}

	auto x = ar.in_groups(4);

	for (int i : step(x.size()))
	{
		for (int k : step(x[i].size()))
			Print(x[i][k]);
		
		Print();
	}

	while (System::Update()) {}
}

/*
出力結果
0
1

2

3

4
*/

**Comment by Reputeless** [comment]
Fixed. Thanks.
