### ISSUE TITLE
Graphics::SetFullScreen()について

### ISSUE THREAD

**Issue by sknjpn** [Siv3D/OpenSiv3D#190]
Graphics::SetFullScreen()を使ってフルスクリーンになる瞬間に、画面を左クリックをしてしまうと灰色のウィンドウになって動作が停止してしまうようです。

試したところ、フルスクリーンが完了した後にならば左クリックは影響ないようです。
![default](https://user-images.githubusercontent.com/29691164/29112468-f180f504-7d28-11e7-8023-2ebaba18ec7f.png)

    # include <Siv3D.hpp>
    
    void Main()
    {
    	Graphics::SetFullScreen(true, Size(1280, 720));
    
    	while (System::Update())
    	{
    		Circle(Window::Center(), 120).draw(Palette::Skyblue);
    	}
    }

**Comment by Reputeless** [comment]
同様の検証を確認しました。調査します。

**Comment by SKN-JP** [comment]
全角キーを押して、何らかのキーを押してしまうとフルスクリーン化が終了した後でも以下の状態になってしまうようです。

![default](https://user-images.githubusercontent.com/29691164/30099597-250626de-9321-11e7-9d7d-ec5a7f2732b1.png)

**Comment by Reputeless** [comment]
フルスクリーンが解除される問題は未解決ですが、応答しなくなる問題は v0.1.7 で修正しました。

**Comment by Reputeless** [comment]
OpenSiv3D v0.4.0 で解決しました。
