### ISSUE TITLE
Windowsでのデバック実行処理の不具合について

### ISSUE THREAD

**Issue by NortonGitHub** [Siv3D/OpenSiv3D#196]
先程、OpenSiv3D0.1.6を使用し、サンプルソースコードを実行しようとしたところ、
ビルドはうまくいくのですがDebugの際にウィンドウが開かず実行が終了してしまいました。

私の開発環境ですが、

OS:
- Windows10 Home 64bit
- version 1703
- Intel Core i7-7600 3.40GHz
- RAM : 8GB
NVIDIA GeForce GTX970 搭載

IDE:
- Visual Studio Community 2017
- Version 15.3.1

またデバックの際の出力結果は以下のアップローダの通りです。

http://textuploader.com/d6kuy

**Comment by Reputeless** [comment]
ログ出力の URL が無効になっているので、再度直接掲載していただけませんか。
最後の十行程度で大丈夫です。

**Comment by NortonGitHub** [comment]
> reputeless さん
申し訳ありませんでした。
以下にデバッグ処理の出力結果を上げ直させていただきました。
https://drive.google.com/file/d/0B_dPsH39QoGqaXRYRlRLSm14VVU/view?usp=sharing

**Comment by Reputeless** [comment]
このエラーメッセージは `FILE* file = fopen("C:/...", "rb" );`
に失敗したときに出力されます。
環境の問題と思われますので、こちらでは追加の調査はできません。
新しい情報がわかったらご報告ください。

**Comment by NortonGitHub** [comment]
大変遅れてしまいましたが上記のデバッグ実行の問題を解決できました。
Ryo Suzuki様のご指摘の通り、管理者アカウントの名前を日本語にしていたための環境の問題でした。
対応して頂いた皆様、本当にありがとうございました。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。サードパーティライブラリ内の問題ということ、承知しました。今後対応が必要な事項として記録しておきます。
