### ISSUE TITLE
バージョンアップについて

### ISSUE THREAD

**Issue by SKN-JP** [Siv3D/OpenSiv3D#200]
既存のOpenSiv3Dプロジェクトを最新のOpenSiv3Dプロジェクトに変更するためにはどのようにすれば良いのでしょうか？

**Comment by Reputeless** [comment]
現在の OpenSiv3D には簡単なバージョンアップの方法はありません。
プロジェクトファイルや Engine ファイル等の差分を確認して手動で行ってください。
