### ISSUE TITLE
Rectについて

### ISSUE THREAD

**Issue by SKN-JP** [Siv3D/OpenSiv3D#206]
`Rect(Line(Vec2(20,40),Vec2(120,80)))`
みたいな感じで対角線でRectを初期化できるようにしてもらいたいです

もし、Vec2 p1とVec2 p2があり、p1,p2の大小関係が分からない場合に
`Rect(Min(p1.x, p2.x), Min(p1.y, p2.y), Abs(p1.x - p2.x), Abs(p1.y - p2.y))`
とする必要があるので。

**Comment by Reputeless** [comment]
点の集合を包含する最小の Rect や Circle を計算する機能を将来的に実装します。

**Comment by Reputeless** [comment]
OpenSiv3D v0.2 に `RectF Line::boundingRect()` として実装しました。ご提案ありがとうございます。
https://github.com/Siv3D/OpenSiv3D/blob/u_update_develop/Siv3D/src/Siv3D/Line/SivLine.cpp#L80
