### ISSUE TITLE
Audioの再生位置取得・変更についての要望

### ISSUE THREAD

**Issue by Rare25** [Siv3D/OpenSiv3D#275]
Siv3DのSoundにあった、以下の関数のAudioへの実装をお願いしたいです。
`Sound::setPosSec()`
`Sound::setPosSample()`
`Sound::posSec()`
`Sound::streamPosSec()`

**Comment by Reputeless** [comment]
移植作業の優先度を上げます。

**Comment by Reputeless** [comment]
v0.2.7 で
`Audio::setPosSample()`
`Audio::setPosSec()`
`Audio::posSec()`
`Audio::streamPosSample()`
がそろいました。
