### ISSUE TITLE
Script_Circle.cppのdrawFrame()のデフォルト値がC++と違う

### ISSUE THREAD

**Issue by ongaeshi** [Siv3D/OpenSiv3D#296]
C++だと1.0のthicknessがスクリプトだと0.0になっているようです

- https://github.com/Siv3D/OpenSiv3D/blob/master/Siv3D/include/Siv3D/Circle.hpp#L474
- https://github.com/Siv3D/OpenSiv3D/blob/master/Siv3D/src/Siv3D/Script/Bind/Script_Circle.cpp#L118

**Comment by Reputeless** [comment]
ご報告ありがとうございます。v0.3.1 から修正が反映されます。
