### ISSUE TITLE
Visual Studio 2017 15.9.1でビルドに失敗する

### ISSUE THREAD

**Issue by ongaeshi** [Siv3D/OpenSiv3D#297]
Visual Studio 2017 を最新の15.9.1に更新した後、ビルドに失敗するようになりました。

以前使っていたバージョン(おそらく15.7)ではビルドできていました。
Windows SDK 10.0.17134.0 はインストール済みです。

![image](https://user-images.githubusercontent.com/154418/48670898-6eeb3c80-eb63-11e8-9196-4c15820481db.png)

**Comment by Reputeless** [comment]
修正します。
