### ISSUE TITLE
Linux 版の README で、必要ライブラリに libogg, libvorbis を追加

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#305]
reported by
- https://twitter.com/Osmium_1008/status/1141195420409839616
- https://twitter.com/Osmium_1008/status/1141196991667421184

**Comment by wynd2608** [comment]
https://github.com/Siv3D/OpenSiv3D/commit/cc6154e60acf2db8225fd77dbc07f0b637eb244c で対応済み。 
ただし、`linux` ブランチには含まれていなかったので、 `linux_develop` を `linux` にマージした( https://github.com/Siv3D/OpenSiv3D/pull/306 )。
