### ISSUE TITLE
複数の戻り値を持つGetPrivateIPv4が欲しい

### ISSUE THREAD

**Issue by Nagarei** [Siv3D/OpenSiv3D#312]
複数のネットワークに接続している環境では複数のIPアドレスを持っているので、それらを全て取得できるようになると嬉しいです。

僕の手元の環境ではDocker用の内部ネットワークがあり、GetPrivateIPv4の結果が10.0.xx.xxとなってしまい192.168.xx.xxのIPアドレスが取れないです。

個人的には急いで無いのでそのうちでお願いします。

**Comment by wynd2608** [comment]
linux版を https://github.com/Siv3D/OpenSiv3D/pull/313 で実装しました

**Comment by Reputeless** [comment]
`getMachineIP()` では、Array の中から 192.168.xx を優先して返すような実装にすると良いと思います。

**Comment by wynd2608** [comment]
このissueに関連して、Linux版でしか確認していないのですが、Network::GetPrivateIPv4()とNetwork::GetPrivateIPv4s()どちらでも、NICにグローバルIPが振られていてもそのアドレスを取得できるので、関数名を変えるか、関数名通りにグローバルIPしか返さないようにした方が良いのでははないでしょうか。
全てのIPアドレスが返ってくれば、ライブラリの利用者側で好きに処理できるので、自分としては取り敢えずでも関数名を変えるのが良いと思います。

**Comment by Reputeless** [comment]
開発中の v0.6 で対応完了しました。
`Network::EnumerateIPV4Addresses()`
