### ISSUE TITLE
ColorFとColorの扱いについて

### ISSUE THREAD

**Issue by sknjpn** [Siv3D/OpenSiv3D#318]
`auto color = Palette::Orange : ColorF(Palette::Blue, 0.1);`
がエラーを吐いてしまうのですが、
`auto color = ColorF(Palette::Orange) : ColorF(Palette::Blue, 0.1);`
のようにするしかないでしょうか？

今確認できる手段がないのですが、0.3.1だとエラーがなかったように思います。

**Comment by Reputeless** [comment]
MSVC, v0.3.2 で軽く試したら、前者は可能でした。v0.4.0 以降は
```C++
auto color1 = true ? ColorF(Palette::Orange) : ColorF(Palette::Blue, 0.1);
auto color2 = true ? Palette::Orange : ColorF(Palette::Blue, 0.1).toColor();
```
のどちらかになります。

```C++
Palette::Orange.toColorF()
```
のような 関数も検討します。

**Comment by sknjpn** [comment]
了解です。ありがとうございます。
