### ISSUE TITLE
SIV3D_WINDOWS_HIGH_DPI定義時のWindow::Resize()の挙動について

### ISSUE THREAD

**Issue by Rare25** [Siv3D/OpenSiv3D#374]
HiDPI表示のとき、`SIV3D_WINDOWS_HIGH_DPI`を定義すると、デフォルトの800x600のウィンドウはドットバイドットで表示されるが、`Window::Resize()`でウィンドウサイズを変更すると、正しく表示されない。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
v0.4.1 にて問題の workaround を実装しました。
正確な処理ではないので、数ピクセルの誤差が生じるかもしれません。

**Comment by Reputeless** [comment]
現在開発中の v0.6 でこの問題に対処中です。

**Comment by Reputeless** [comment]
開発中の v0.6 で正確な解像度にリサイズするよう修正されました。
v0.6 では High-DPI が標準になります。
