### ISSUE TITLE
文字コードの変換について

### ISSUE THREAD

**Issue by Jin3004** [Siv3D/OpenSiv3D#376]
Unicode名前空間にある関数群でどのような文字コードでも変換できる、っていうのはゲームライブラリとしてかなりの強みだと思うので、リファレンスに書くべきだと思います。

**Comment by Reputeless** [comment]
done: https://siv3d.github.io/ja-jp/reference/unicode/
なお、すでにチュートリアルでは一部解説: https://siv3d.github.io/ja-jp/tutorial/data-structures/#_10
