### ISSUE TITLE
DirectoryWatcherでの空のディレクトリの監視

### ISSUE THREAD

**Issue by wynd2608** [Siv3D/OpenSiv3D#391]
現在のDirectoryWatcherの実装では、渡されたパスのディレクトリの中身が空の場合にエラーで終了するようになっています。
https://github.com/Siv3D/OpenSiv3D/blob/master/Siv3D/src/Siv3D-Platform/WindowsDesktop/DirectoryWatcher/DirectoryWatcherDetail.cpp#L20
https://github.com/Siv3D/OpenSiv3D/blob/master/Siv3D/src/Siv3D-Platform/macOS/DirectoryWatcher/DirectoryWatcherDetail.cpp#L32

しかし、空のディレクトリにファイルやディレクトリが作られるのを監視する処理を行うこともあり得るように思われるので、空のディレクトリに対しても監視を行えるようにしたほうが良いのではないでしょうか。

**Comment by Reputeless** [comment]
`directory.isEmpty()` は、空の文字列のチェックです。
問題なければ issue を close してください。

**Comment by wynd2608** [comment]
ソースコード確認しました。勘違いでissueたててしまってすみません。🙇
