### ISSUE TITLE
Cursor::Pos()と実際のカーソルとのズレが大きい

### ISSUE THREAD

**Issue by Rare25** [Siv3D/OpenSiv3D#392]
旧Siv3Dの`Mouse::Pos()`に比べると、実際のカーソルの位置とのズレが大きい。

**Comment by Reputeless** [comment]
調査します。

**Comment by Rare25** [comment]
意図が書けていなかったので追記します。サンプルコードにあるような、円をカーソルの位置に描画するプログラムを書くと、カーソルを大きく速く動かしたときに、カーソルの位置ではなく、追従するような位置になってしまうということです。
垂直同期を切ると問題無いので、同期の都合上難しいのでしょうか？

**Comment by Reputeless** [comment]
Windows 版について、OpenSiv3D のどこかのバージョン以降、1 フレーム遅くなっていたようです。
v0.6 で修正が入りました。
