### ISSUE TITLE
リファレンスのGIFが再生されない

### ISSUE THREAD

**Issue by Jin3004** [Siv3D/OpenSiv3D#395]
OpenSiv3Dのリファレンスのこのページ( https://siv3d.github.io/ja-jp/tutorial/effect/ )を見たとき、GIFが再生されずにどのようなエフェクトなのか分からないです。

**Comment by Reputeless** [comment]
MP4 ムービーです。GIF ではありません。
OS とブラウザのバージョンを書いてください。
通信速度が遅くて表示されていない可能性もあります。

**Comment by Jin3004** [comment]
iOSとChrome(76.0.3809.123)ですね。何回かリロードしましたが、やはり動きません。

**Comment by Jin3004** [comment]
PCで見ると、ちゃんと再生されていますね。
通信速度の問題ではないと思います。

**Comment by Reputeless** [comment]
ブラウザの設定やキャッシュなど、環境固有の問題と思われます。
対応策がない/わからないので close します。

**Comment by Reputeless** [comment]
https://deep-space.blue/web/822 が関連してるかもしれません。
手元の iPadOS 13.1 /Chrome 76 では再生されます。

**Comment by Jin3004** [comment]
なるほど。。
