### ISSUE TITLE
Cursor::Pos()が画面の右に進むほどカーソルの位置からズレる

### ISSUE THREAD

**Issue by hiroki19990625** [Siv3D/OpenSiv3D#403]
## 詳細
Cursor::Pos()が画面の右に進むほどカーソルの位置がズレてしまいます。
また、Cursor::Pos()の影響なのか、SimpleGUI::Button()の判定もズレてしまいます。
スクリーンショットのコードはVisualStudioでプロジェクト作成のサンプルです。
他のバージョンで試した結果なのですが、OpenSiv3Dの0.3.2では正常に動作しますが、
0.4.0からズレてしまいます。

## スクリーンショット
![スクリーンショット (11)](https://user-images.githubusercontent.com/18022692/67628199-ddbd3380-f8a4-11e9-91ab-ae97ae2d28e4.png)

![スクリーンショット (12)](https://user-images.githubusercontent.com/18022692/67628211-e281e780-f8a4-11e9-8c80-defb2de4b17c.png)

## ログファイル
[OpenSiv3D(0.4.1)1(debug)_log.zip](https://github.com/Siv3D/OpenSiv3D/files/3775440/OpenSiv3D.0.4.1.1.debug._log.zip)

**Comment by Reputeless** [comment]
ディスプレイ→表示スケールの詳細設定→カスタムスケーリング
を設定しないようにすれば発生しません。
![image](https://user-images.githubusercontent.com/3108136/67631068-c26a1c80-f8d4-11e9-967f-0c97863b5abf.png)

**Comment by hiroki19990625** [comment]
ありがとうございます。
発生しなくなりました！
