### ISSUE TITLE
Linux版MessageBoxの改善

### ISSUE THREAD

**Issue by wynd2608** [Siv3D/OpenSiv3D#431]
- フォントの描画
- タブ等の制御文字の扱い
- メインループ以外で使うとアプリケーション側の応答が無いとメッセージが出る問題

**Comment by wynd2608** [comment]
WindowsのMessageBoxはタブや改行を扱えないので、現状で改行ができる状態でOKとして、それ以外の制御文字が文字列中にあったら無視するというやり方でも良さそうです。 (11/24実装会での相談結果)

**Comment by wynd2608** [comment]
#448 確認してマージました。

メインループ以外で使うとアプリケーション側の応答が無いとメッセージが出る問題の解決の方はどうですか？

**Comment by kurokoji** [comment]
@wynd2608 実は今，別のマシン(マシンスペックが上昇している)で開発しているのですが，アプリケーション側の応答が無い旨のメッセージが出ません．wyndさんの環境ではどうなるか一旦教えてもらってもよろしいですか?

**Comment by wynd2608** [comment]
@kurokoji 現在、主に開発に使っている環境は、i7-7700k, gtx1070, メモリ32g, archlinux, cinnamon 4.4.4, g++ 9.2.0 or clang 9.0.0ですが、これまでにメインループの外でメッセージボックスを表示するコードを実行して、「応答が無い」といったメッセージが出たことはありません。
htopとかでメッセージボックス表示中のプログラムのプロセスの状態を見ると「S」と出ているので特に問題は無いんじゃないかと思っています。

**Comment by kurokoji** [comment]
スペックの問題なんでしょうかね... ちょっと原因がわからないです

**Comment by wynd2608** [comment]
多分ですが、スペックの問題ということは無いと思います。
過去に応答が無いとメッセージが出た環境と、別のマシンになってメッセージが出なくなった環境はそれぞれどういったものですか？　自分の方でも似た環境が用意できそうならチェックしてみます。

**Comment by kurokoji** [comment]
旧環境: ThinkPad X240, i3-4010U, RAM4GB, Manjaro GNOME 18.1.4
現環境: ThinkPad E450,  i7-5500U, RAM8GB, ArchLinux i3-gaps

**Comment by kurokoji** [comment]
先程，現環境のArchLinuxにGNOMEをインストールして実行したところ，応答が無い旨のメッセージが表示されました．ただし，旧環境と違いフリーズすることはありませんでした．
