### ISSUE TITLE
ParticleSystem2DParameters::startAngularVelocityDegの値の正負の仕様の改善

### ISSUE THREAD

**Issue by falrnd** [Siv3D/OpenSiv3D#433]
ParticleSystem2DParametersについて  
パーティクルの回転速度のパラメータであるstartAngularVelocityDegに正の値と負の値を設定できるが  
randomAngularVelocityがtrueの場合に±Abs(回転速度)の範囲の乱数で回転速度を設定しているためパラメータの正負が意味をなしていない  

https://github.com/Siv3D/OpenSiv3D/blob/master/Siv3D/src/Siv3D/ParticleSystem2D/ParticleSystem2DDetail.cpp#L189

**Comment by Reputeless** [comment]
仕様を改善しました。
