### ISSUE TITLE
EngineError: ID3D11Device::CreateTexture2D() failed

### ISSUE THREAD

**Issue by SK-Legno** [Siv3D/OpenSiv3D#451]
サンプルコードを実行するとビルドしているときに[EngineError: ID3D11Device::CreateTexture2D() failed]と表示されビルドが止まってしまいます。

**Comment by Reputeless** [comment]
それはビルドエラーではなく実行時エラーです。
どのプログラムですか。

**Comment by SK-Legno** [comment]
サンプルプログラムで実行しました

**Comment by SK-Legno** [comment]
[test_1.zip](https://github.com/Siv3D/OpenSiv3D/files/3982547/test_1.zip)

**Comment by Reputeless** [comment]
(1) これは初めてですか？
(2) PC を再起動するとどうですか？
(3) エラー発生時の Visual Studio の出力ウィンドウの内容をテキストで共有してください（「デバッグなしで実行」だと出ないので注意）
![image](https://user-images.githubusercontent.com/3108136/71158833-ecfaa500-2287-11ea-9675-66b49c3fe741.png)
(4) 実行環境の PC スペックを教えてください

**Comment by SK-Legno** [comment]
返答が遅くなり申し訳ございません。調べたところ自分の開発環境のノートパソコンのハードの問題だとわかりました。お手数をおかけしました。ありがとうございました。
