### ISSUE TITLE
入力されたキーの一覧を取得する

### ISSUE THREAD

**Issue by mattyan1053** [Siv3D/OpenSiv3D#486]
現状個別に指定のキー入力状況を取得するような感じだったと思うのですが、旧Siv3Dにあった`Input::GetActiveKeys()`のようなものがあると便利かと思いました。

**Comment by Reputeless** [comment]
開発中の OpenSiv3D v0.6 に `Mouse::GetAllInputs()`, `Keyboard::GetAllInputs()` として実装しました。
