### ISSUE TITLE
Math::InvSqrt2_v の値について

### ISSUE THREAD

**Issue by voidproc** [Siv3D/OpenSiv3D#493]
https://github.com/Siv3D/OpenSiv3D/blob/winmac_develop/Siv3D/include/Siv3D/MathConstants.hpp#L36
この行ですが、実際の値は 0.70710678118654746... ではないかなと思います。

**Comment by Reputeless** [comment]
修正しました！ v0.4.3 (release) から反映されます。

**Comment by voidproc** [comment]
素早い対応ありがとうございます！
