### ISSUE TITLE
ウィンドウサイズを手動で変更したとき、カーソルが元に戻らない

### ISSUE THREAD

**Issue by Rare25** [Siv3D/OpenSiv3D#501]
`Window::SetStyle(WindowStyle::Sizable)` を実行して、ウィンドウの端を掴んで手動でサイズを変更すると、ウィンドウ内に戻ったときに元のカーソルに戻らない。タイトルバーに触れると戻る。

**Comment by Reputeless** [comment]
開発中の OpenSiv3D v0.6 でこの問題は解消しました。
ご報告ありがとうございました。
