### ISSUE TITLE
Linuxでサンプルアプリのビルドがリンクエラーになる

### ISSUE THREAD

**Issue by taotao54321** [Siv3D/OpenSiv3D#503]
Debian testing で Linux/App 以下のサンプルアプリをビルドすると、リンク時に各種ライブラリのシンボルが見つけられず undefined reference エラーになるようです。

おそらく原因はコンパイラに渡す引数の順序で、
https://github.com/Siv3D/OpenSiv3D/blob/linux_develop/Linux/App/CMakeLists.txt#L39
で libSiv3D.a がライブラリリストの末尾にあるのが問題かと思われます。これを先頭へ移動したら正しくリンクでき、アプリも正常動作しました。

**Comment by Reputeless** [comment]
v0.4.3 で対応しました。ご報告ありがとうございました。
