### ISSUE TITLE
Linux で Window::Resize() するとウィンドウが画面外へ移動する

### ISSUE THREAD

**Issue by taotao54321** [Siv3D/OpenSiv3D#506]
Debian testing の Xfce (シングルモニタ)環境で Window::Resize() を行うと、ウィンドウが画面外へ飛んでしまい、デスクトップ左下隅にウィンドウの右上隅(閉じるボタン部分)のみが見えている状態になるようです。

リサイズに伴うセンタリング処理内でワークエリアがうまく取得できていないのが原因と思われます。
モニタ情報のみを出力するプログラムを書いて調べてみたところ:
https://gist.github.com/taotao54321/b7c0c6346b4900c0f5ee8b57d3092154

このような結果になり、ワークエリアが正しく取得できていませんでした:
![workarea](https://user-images.githubusercontent.com/21364118/79069462-63c11f80-7d09-11ea-98e6-4aa328c493f3.png)

とりあえずの対処として、Window::Resize() の centering 引数に false を指定し、センタリングを無効にすれば意図通りに動作するようです。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。対処します。
