### ISSUE TITLE
Audio::playOneShotで左右のvolumeを変えたいです

### ISSUE THREAD

**Issue by tyanmahou** [Siv3D/OpenSiv3D#513]

**Comment by Reputeless** [comment]
v0.6 の `Audio::playOneShot(size_t busIndex = 0, double volume = 1.0, double pan = 0.0, double speed = 1.0)`;
で、pan を設定できるようになりました。ご提案ありがとうございました。
https://github.com/Siv3D/OpenSiv3D/blob/v6_winmac_develop/Siv3D/include/Siv3D/Audio.hpp

再生後の制御についても将来のバージョンで実装予定です。
