### ISSUE TITLE
Bitmapフォントの描画にアンチエイリアスがかかってしまう

### ISSUE THREAD

**Issue by tyanmahou** [Siv3D/OpenSiv3D#514]
### 詳細メモ
FontStyleをBitmapにしたり、SamplerStateをNearestにしたり試しましたが上手くいきませんでした。

使用フォント: PixelMplus12-Regular.ttf

**Comment by tyanmahou** [comment]
対象のフォント自体が
ただのアウトラインフォントでBitmapフォントの埋め込みはされてないようでした

http://itouhiro.hatenablog.com/entry/20130602/font

**Comment by Reputeless** [comment]
開発中の OpenSiv3D v0.6 にて、フォントの実装を刷新し、問題を解決しました。
ご報告ありがとうございました。

（上: v0.4.3, 下: v0.6）

![image](https://user-images.githubusercontent.com/3108136/107375962-aec7e100-6b2c-11eb-8f6b-423929a6002f.png)

![image](https://user-images.githubusercontent.com/3108136/107375806-7c1de880-6b2c-11eb-9c67-2da36bcabfef.png)

```cpp
const Font font1{ 24, U"PixelMplus12-Regular.ttf", FontStyle::Bitmap };
const Font font2{ 36, U"PixelMplus12-Regular.ttf", FontStyle::Bitmap };
const Font font3{ 96, U"PixelMplus12-Regular.ttf", FontStyle::Bitmap };
```

**Comment by tyanmahou** [comment]
対応ありがとうございました。
