### ISSUE TITLE
Linux で System::EnumerateGamepads() を呼ぶと SEGV で落ちる

### ISSUE THREAD

**Issue by taotao54321** [Siv3D/OpenSiv3D#516]
USB ゲームパッドを接続し、以下のコードを Linux で実行すると SEGV で落ちてしまいます。また、ゲームパッドの検出自体もできていないようです。

```cpp
#include <Siv3D.hpp>

void Main() {
    for(const auto& info : System::EnumerateGamepads())
        Print << U"[{}]_{}"_fmt(info.index, info.name);

    while(System::Update()) {}
}
```

gdb で調べたところ、`_siv3d_PlatformGetJoystickInfo()` 内の `udev_device_new_from_subsystem_sysname()` 呼び出しで落ちているようです。

USB ゲームパッドは AT-P01 (PlayStation コントローラ変換器)です。また、USB ゲームパッドを接続せずに上記コードを実行すると `EnumerateGamepads()` から返ってこなくなるようです。

SDL2 ソースツリーに含まれる testjoystick では正常に検出できています:

```
INFO: Joystick device 0 added.
INFO: Joystick
INFO:        name: Austgame PS TO USB CONVERTOR
INFO:        type: Unknown
INFO:        axes: 4
INFO:       balls: 0
INFO:        hats: 1
INFO:     buttons: 12
INFO: instance id: 0
INFO:        guid: 03000000730700000102000000010000
INFO:     VID/PID: 0x0773/0x0201
```

lsusb の出力:

```
Bus 002 Device 002: ID 0773:0201 Austgame PS TO USB CONVERTOR
```

環境は Debian testing です。各種パッケージのバージョンは以下の通りです:

Siv3d 8fbb0d1
linux-image-amd64 5.5.17-1
libudev 245.5-2

**Comment by Reputeless** [comment]
開発中の OpenSiv3D v0.6 でこの問題を修正しました。
ご報告ありがとうございました。
