### ISSUE TITLE
SDFFontで一部フォントがぼやけた描画になってしまう。

### ISSUE THREAD

**Issue by ITRX** [Siv3D/OpenSiv3D#517]
SDFFontを使用して文字列を描画したのですが、一部フォント(msgothic.ttcやmsmincho.ttc)などで下の画像のようにぼやけた感じの描画になってしまいます。
<img width="150" alt="20200505-195725-605" src="https://user-images.githubusercontent.com/38271091/81059128-d4271f00-8f0a-11ea-88c6-c1b4e09a3299.png">
上がSDFFontで描画した結果、下がFontで描画した結果で、どちらも使用しているフォントはmsgothic.ttcです。

ソースコードは以下の通りです

```
void Main() {
  Scene::SetBackground(Color(0,0,255));

  SDFFont font_sd(80, FileSystem::SpecialFolderPath(SpecialFolder::SystemFonts) + U"msgothic.ttc");
  Font font_n(40, FileSystem::SpecialFolderPath(SpecialFolder::SystemFonts) + U"msgothic.ttc");

  while (System::Update()) {
    Graphics2D::SetSDFParameters(font_sd.pixelRange());
    font_sd(U"ABC123あいう").draw(40, Vec2(20, 30));
    font_n(U"ABC123あいう").draw(20, 80);
  }
}
```

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
一部のフォントファイルは、SDF パラメータに関して、調整が必要なようです。
msgothic.ttc は `font_sd.pixelRange() * 4` あたりに変更することで適切に表示されると思います。
今後原因を調査します。

**Comment by ITRX** [comment]
ありがとうございます。
適切な描画ができました。

**Comment by Reputeless** [comment]
v0.6 で SDF フォントの実装を刷新したところ、ご報告いただいた問題が解消しました（原因の特定はできませんでした）。
ご報告ありがとうございました。
