### ISSUE TITLE
Can make work on emiscripten / webassembly?

### ISSUE THREAD

**Issue by paklau99988** [Siv3D/OpenSiv3D#530]
Want put game on web, is possible? 
Thanks you

**Comment by Reputeless** [comment]
There is an experimental fork to port OpenSiv3D to web.
- repo: https://github.com/nokotan/OpenSiv3D
- guide (Japanese): https://qiita.com/nokotan/items/8fc8a3c0837ac2f532f4
- maintainer: @nokotan

I have a long-term plan to merge above functionalities into the official OpenSiv3D repository. (v0.6.x or later)

**Comment by paklau99988** [comment]
OK, 
I wait when ready, many thanks for long reply. Is japanese no understand.

**Comment by nokotan** [comment]
I just translated "OpenSiv3D for Web" guild to English, which will help you...

[Qiita - WebGL game development with OpenSiv3D for Web (VSCode on Windows)](https://qiita.com/nokotan/items/7fdb71b39901132b4014)
