### ISSUE TITLE
Listbox is required among UI controls

### ISSUE THREAD

**Issue by jacking75** [Siv3D/OpenSiv3D#536]
Hello
I want to use the listbox controller because I want to show previously printed messages in chat, etc.
There is no listBox among UI controls, are there any plans to create in the future?
How do I create a listbox control with the current functionality?

**Comment by Reputeless** [comment]
OK, I will make an example code in a few days.

**Comment by Reputeless** [comment]
リストボックス `UIToolkit::ListBox`
https://zenn.dev/reputeless/articles/73f6e98e1201e4bad42e

![ListBox](https://user-images.githubusercontent.com/3108136/95733583-51766d00-0cbd-11eb-9685-be277d392d71.gif)

**Comment by jacking75** [comment]
Thank you very much
