### ISSUE TITLE
ドキュメントの誤植

### ISSUE THREAD

**Issue by Ebishu-0309** [Siv3D/OpenSiv3D#537]
https://siv3d.github.io/ja-jp/tutorial/text-file/#183
「18.3 ファイルにテキストを書き込む」において、サンプルコードのシンタックスハイライトが消えています。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。確認しました。まもなく修正、更新します。
ドキュメントへの Issue は https://github.com/Siv3D/siv3d.docs/issues を推奨しています。
