### ISSUE TITLE
Array.hppのUbuntuでのCompile error

### ISSUE THREAD

**Issue by nekomimimi** [Siv3D/OpenSiv3D#538]
コンパイル時にエラーになりましたのでご報告いたします。
インストールを手伝った時にリモートで見かけたので環境が手元になく、なにかインストールの手違い等でしたらごめんなさい。

◇ 
Siv3D/include/Siv3D/Array.hppの2230行、 2301行、Returnに戻り値がなくエラーになってるような印象で下記のメッセージが出ました。

◇ Error message
../../Siv3D/include/Siv3D/Array.hpp:2230:5: error: return-statement with no value, in function returning ‘s3d::Array<Type, Allocator>&’ [-fpermissive]
 2230 |     return;
      |     ^~~~~~
../../Siv3D/include/Siv3D/Array.hpp: In member function ‘const s3d::Array<Type, Allocator>& s3d::Array<Type, Allocator>::parallel_each(Fty) const’:
../../Siv3D/include/Siv3D/Array.hpp:2301:5: error: return-statement with no value, in function returning ‘const s3d::Array<Type, Allocator>&’ [-fpermissive]
 2301 |     return;
      |     ^~~~~~

環境：ubuntu

**Comment by Reputeless** [comment]
ご報告ありがとうございます！修正しました。

**Comment by nekomimimi** [comment]
ありがとうございますm(_ _)m
