### ISSUE TITLE
WM_DEVICECHANGE の発生時にクラッシュすることがある問題

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#550]
- report: https://siv3d.jp/bbs/patio.cgi?read=506&ukey=0

**Comment by furafura2020** [comment]
X299-GAMING-PRO-CARBON-AC on-board sound device
Realtek HD Audio Drivers 6.0.1.8619

**Comment by Reputeless** [comment]
オーディオよりも
`Siv3DEngine::Get<ISiv3DGamepad>()->update(onDeviceChange); `
に問題がある可能性の報告。
https://siv3d.jp/bbs/patio.cgi?read=509

**Comment by Reputeless** [comment]
@furafura2000 さんが Siv3D BBS で報告してくださった情報をもとに調査した結果、WM_DEVICECHANGE イベント発生時の joy〜 関数がクラッシュを誘発している可能性が濃厚になりました。
他のフレームワークを参考にし、OpenSiv3D v0.6 ではゲームパッドの情報取得に DirectInput を使用することで問題を回避します。現在置き換え作業を進めています。

**Comment by furafura2020** [comment]
対応ありがとうございます。これからも発展される事を願っております。

**Comment by Reputeless** [comment]
置き換え作業完了、joy〜 関数の使用を廃止。

**Comment by furafura2020** [comment]
遅くなりましたが0.62での動作報告です。
以前問題が出ていたWM_DEVICECHANGE続出環境で、
プロジェクト開始時のサンプルにて数日間動作させ続けましたが、問題は起きませんでした。
改めまして、対応いただいて本当にありがとうございました。

**Comment by Reputeless** [comment]
動作報告ありがとうございます。安心しました。
長らく続いていた問題なので、本 Issue で原因究明 + 解決できて良かったです。
