### ISSUE TITLE
ダイアログを開いたあとにCursorStyle::Hiddenを使ってもマウスカーソルが隠れなくなる

### ISSUE THREAD

**Issue by yurkth** [Siv3D/OpenSiv3D#555]
`CursorStyle::Hidden`を使ってカーソルを非表示にしているときに、ファイルダイアログを開いて閉じるとカーソルが現れてしまいます。
一度カーソルをウィンドウの外に移動するともとに戻ります。

Windows版のv0.4.3で確認しました。
以下のコードで再現できます。

#501 と関連するかもしれません。

```cpp
#include <Siv3D.hpp> // OpenSiv3D v0.4.3

void Main() {
    while (System::Update()) {
        if (SimpleGUI::Button(U"FileDialog", { 10, 10 })) {
            Dialog::OpenFile();
        }
        Cursor::RequestStyle(CursorStyle::Hidden);
        Circle(Cursor::Pos(), 4).draw(Palette::Red);
    }
}
```

ファイルダイアログを開く前
![before](https://user-images.githubusercontent.com/59264002/105629082-45857400-5e84-11eb-917f-8e7a44b4737f.png)

ファイルダイアログを閉じたあと
![after](https://user-images.githubusercontent.com/59264002/105629085-4ae2be80-5e84-11eb-8220-1f73226e333c.png)

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
v0.6 で Windows 版のカーソルの Hidden 時のコードを改良しています。こちらの問題も直るのではないかと期待しています。
v0.6 では Dialog が未実装で、すぐには検証できませんが、チェック項目に加えます。

**Comment by yurkth** [comment]
承知しました。
よろしくお願いします。

**Comment by Reputeless** [comment]
現在開発中の v0.6 で修正・解決したことを確認しました。
ご報告ありがとうございました。

**Comment by yurkth** [comment]
ありがとうございます！
