### ISSUE TITLE
ボタンの中の文字がぼやける

### ISSUE THREAD

**Issue by polyester-CTRL** [Siv3D/OpenSiv3D#556]
![フォト 2021_01_26 17_49_03](https://user-images.githubusercontent.com/56536708/105821982-d3856a00-5ffe-11eb-9f4e-508e891a6e7b.png)
Windowsで実行した際、ボタンの中の文字がぼやけて見えます。
ソースコードは[https://siv3d.github.io/ja-jp/](https://siv3d.github.io/ja-jp/)に記載されているものです。
` #include <Siv3D.hpp>

void Main()
{
    // 背景を水色にする
    Scene::SetBackground(ColorF(0.8, 0.9, 1.0));

    // 大きさ 60 のフォントを用意
    const Font font(60);

    // 猫のテクスチャを用意
    const Texture cat(Emoji(U"🐈"));

    // 猫の座標
    Vec2 catPos(640, 450);

    while (System::Update())
    {
        // テキストを画面の中心に描く
        font(U"Hello, Siv3D!🐣").drawAt(Scene::Center(), Palette::Black);

        // 大きさをアニメーションさせて猫を表示する
        cat.resized(100 + Periodic::Sine0_1(1s) * 20).drawAt(catPos);

        // マウスカーソルに追従する半透明の赤い円を描く
        Circle(Cursor::Pos(), 40).draw(ColorF(1, 0, 0, 0.5));

        // [A] キーが押されたら
        if (KeyA.down())
        {
            // Hello とデバッグ表示する
            Print << U"Hello!";
        }

        // ボタンが押されたら
        if (SimpleGUI::Button(U"Move the cat", Vec2(600, 20)))
        {
            // 猫の座標を画面内のランダムな位置に移動する
            catPos = RandomVec2(Scene::Rect());
        }
    }
}`

**Comment by Reputeless** [comment]
High DPI 環境で UI 倍率が 100% より大きくなっていることがおそらく原因です。
![image](https://user-images.githubusercontent.com/3108136/105835374-0df70300-600f-11eb-9c7c-905fddfe49bd.png)
v0.4.3 ではその倍率の分だけ、ウィンドウのコンテンツが拡大され、ぼけてしまいます。（例: 実際のウィンドウの解像度は 1200x900 でもシーンの解像度が 800x600 で描かれている）
v0.4.3 では、以下のようにしてウィンドウ解像度を High DPI 基準に合わせることができます（上の例でいえば、ウィンドウの解像度を 800x600 にする）。ただし、その作用でウィンドウが小さくなってしまいます。

```cpp
// v0.4.3 まで
# define SIV3D_WINDOWS_HIGH_DPI
# include <Siv3D.hpp>
```

v0.6 以降は方式が変わり、シーンの解像度のほうを上げられるようになりました。（上の例で言えば、シーンの解像度を 1200x900 にできる）
SimpleGUI も、それを検知して適切なスケールで描画されるようにする予定です。

**Comment by polyester-CTRL** [comment]
ありがとうございました。
`# define SIV3D_WINDOWS_HIGH_DPI`
を書いたところ、ぼやけることがなくなりました。
v0.6のほうもよろしくお願いします。
