### ISSUE TITLE
Geometry2D::Contains(Circle, Ellipse) が一部のケースで誤っている

### ISSUE THREAD

**Issue by Ebishu-0309** [Siv3D/OpenSiv3D#558]
`Geometry2D::Contains(Circle, Ellipse)` が、このようなギリギリ含まれていないケースにおいて、`true` を返してしまうようです。

検証コード: https://gist.github.com/Ebishu-0309/35ed2f0c4aa5d2288e262a17e3f66c8a

![キャプチャ](https://user-images.githubusercontent.com/47941351/106095351-03f01400-6177-11eb-9a20-419c7dcb7893.JPG)

**Comment by Reputeless** [comment]
とりあえず修正しました。ご報告ありがとうございます。
