### ISSUE TITLE
Siv3D くんのドット絵素材

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#570]
- https://twitter.com/lriki8/status/1365945999668039684

クレジット表記
- 作者名
- （オプション）ファイル名（ドット絵素材の慣習に沿った名前があれば）
- （オプション）作者のメールアドレスまたは URL
- （オプション）利用者へのコメント（ドットサイズなど？）

をお知らせください。@lriki

コミット先等を指示します。

**Comment by lriki** [comment]
@Reputeless  以下、お願いします。

- 作者名
  - LRIKI
- 作者のメールアドレスまたは URL
  - https://twitter.com/lriki8
- 利用者へのコメント
  - [WolfRPGEditor](https://www.silversecond.com/WolfRPGEditor/) 規格のキャラチップ素材です。

### 原本
https://github.com/lriki/Siv3D-PixelArt

**Comment by Reputeless** [comment]
ありがとうございます！
後ほど Pull-req の案内をします！

**Comment by Reputeless** [comment]
- `spritesheet/siv3d-kun-16.png`
  - ドット絵ファイル

- `spritesheet/siv3d-kun-16.txt`
  - UTF-8 (BOM あり) でエンコード

```
Made by LRIKI (https://twitter.com/lriki8)
- Source files: https://github.com/lriki/Siv3D-PixelArt
- This work features an adaptation of Siv3D-kun, (c) 2015 Siv3D, licensed under a CC BY-NC: http://creativecommons.org/licenses/by-nc/4.0/
- WOLF RPG Editor 規格のキャラチップ素材です。
```

以上 2 点を [`v6_winmac_develop`](https://github.com/Siv3D/OpenSiv3D/tree/v6_winmac_develop) ブランチの

- `OpenSiv3D/WindowsDesktop/App/example/`
- `OpenSiv3D/Linux/App/example/`
- `OpenSiv3D/macOS/App/example/`
- `OpenSiv3D/Web/App/example/`

に配置（合計 8 ファイル追加）、という Pull-req でお願いできますか。
Pull-request のコメントにはこの Issue の番号 #570 を含めてください
