### ISSUE TITLE
Transformer2D影響下において、Viewport の描画位置がTransformer2D適用前の位置になる

### ISSUE THREAD

**Issue by ROCKTAKEY** [Siv3D/OpenSiv3D#581]
いつもありがとうございます。
このissueはUbuntu on WSL2においてのもので、~~他の環境については不明です~~ (追記: Visual Studioでも再現しました(後述))。  要約すると、「画面上にViewportを相対座標で配置できない」ということになります。

以下のように、Transformer2Dを適用させた状態でRectオブジェクトを生成し、そのRectを引数にScopedViewport2Dオブジェクトを生成した場合、Rectの描画位置はTransformer2Dの影響を受けているのに対し、Viewportの位置はTransformer2Dの影響を受けません。

以下にあるのは[サンプル](https://siv3d.github.io/ja-jp/tutorial/2d-renderstates/#155)にTransformer2Dの行を加えたコードです。

![image](https://user-images.githubusercontent.com/20369462/116497657-db48f900-a8e2-11eb-8aff-abbc6b77c2fb.png)

```C++
# include <Siv3D.hpp>

void Main()
{
    const Texture cat(Emoji(U"🐈"));

//ここを追加
    Transformer2D t(Mat3x2::Translate(100, 100));

    // ビューポートの領域
    Rect viewportRect(200, 200, 400, 200);
    bool grab = false;

    while (System::Update())
    {
        if (grab)
        {
            viewportRect.pos.moveBy(Cursor::Delta());
        }

        // ミニウィンドウのタイトルバー
        const Rect bar(viewportRect.pos.movedBy(0, -40), viewportRect.w, 40);

        // タイトルバーをつかんで移動
        if (bar.leftClicked())
        {
            grab = true;
        }
        else if (MouseL.up())
        {
            grab = false;
        }

        bar.stretched(2, 2, 0, 2).draw(Palette::Seagreen);
        viewportRect.drawFrame(0, 2, Palette::Seagreen);

        {
            // ビューポートの適用
            const ScopedViewport2D viewport(viewportRect);

            Rect(0, 0, viewportRect.size).draw(ColorF(0.8, 0.9, 1.0));

            Circle(200, 100, 150).draw();

            cat.drawAt(20, 20);
        }
    }
}
```

**Comment by ROCKTAKEY** [comment]
すみません、間違っている気がしてきたので一端閉じます。正しければもう一度開きなおします。

**Comment by ROCKTAKEY** [comment]
やはり正しそうなのでもう一度開きます。
1. 猫と円の描画位置は期待通り(座標変換後のViewportで描画)だが、座標変換に影響されていないViewportにいると考えられる(座標変換後のRectの枠外に出ているため)
2. 長方形の位置は不明だが、おそらく猫や円と同様に、描画位置は期待通り(座標変換後のViewportで描画)で、座標変換に影響されていないViewportにいる。
上記のことがわかります。Viewportの平行移動と座標変換は描画位置においては可換ですので、
1. Viewportの位置は(viewportRectそのものは座標変換の影響を受けているのに)座標変換に影響を受けていない
2. Viewport内の座標系がTransformer2Dの影響で座標変換を受けている(ので結果的に位置だけ正しい)
と思われます。

**Comment by ROCKTAKEY** [comment]
個人的には、Viewportの描画位置がTransformer2Dの影響を全面的に受け、Viewport内の座標系に入った時点でTransformer2Dの影響が無くなるのが自然な挙動かと思います。
あるいは、座標変換とViewportを併用することを前提としていないのであれば、仕様とするのもよさそうだなと考えています。

PRができるほど理解が進んでいない身で強縮ですが、ご報告させていただきます。

**Comment by ROCKTAKEY** [comment]
Visual Studioにおいても試しましたが、同様でした。
![image](https://user-images.githubusercontent.com/20369462/116773489-703d2500-aa90-11eb-98c9-85475514d61b.png)

**Comment by Reputeless** [comment]
Siv3D ユーザコミュニティ Slack にて回答済
https://siv3d.slack.com/archives/C03MZP8SH/p1619877901035100?thread_ts=1619877256.034800&cid=C03MZP8SH

> Viewport は Rect である必要があり、座標変換は適用されません。
> Viewport は何かと不便なので、RenderTexture を使うと良いです。
> https://siv3d.github.io/ja-jp/news/v041/#1
