### ISSUE TITLE
アセット管理 Unregister() と Audio のフェードアウトの組み合わせでクラッシュ

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#585]
- reported by: https://twitter.com/Ryoga_exe/status/1393121616226226181

**Comment by Ryoga-exe** [comment]
状況を再現しました。

https://gist.github.com/Ryoga-exe/bf1c70f8fa320618f45f627625efa0ac

**Comment by Ryoga-exe** [comment]
Audio をメンバ変数で持った場合も同様の現象が発生しました

https://gist.github.com/Ryoga-exe/61fd91c562d993e0d4ab31e33311325d

**Comment by Reputeless** [comment]
再現コードありがとうございます。調査します。

**Comment by Reputeless** [comment]
v0.6 で修正されました。
