### ISSUE TITLE
v0.4.4 Linux 版 MessageBox を v0.6 に反映

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#588]
0b0e22f までの開発成果を v0.6 向けに修正したコード↓
https://gist.github.com/Reputeless/e566780df0711b10d2482cb597b9d9b5
を、@kurokoji さんに `v6_winmac_develop` ブランチにコミットしてもらう。

- 更新するファイル: [Siv3D/src/Siv3D-Platform/Linux/Siv3D/MessageBox/SivMessageBox_Linux.cpp](https://github.com/Siv3D/OpenSiv3D/blob/v6_winmac_develop/Siv3D/src/Siv3D-Platform/Linux/Siv3D/MessageBox/SivMessageBox_Linux.cpp)

**Comment by kurokoji** [comment]
@Reputeless  コミットしました．一応Buildして動作することも確認しました．
