### ISSUE TITLE
AABBの位置指定がCenterに固定されている

### ISSUE THREAD

**Issue by itakawa** [Siv3D/OpenSiv3D#590]
OpenSiv3D0.4.3のAABBについて、仕様上の使い勝手の話ですが、
![image](https://user-images.githubusercontent.com/43272572/119251444-7f237d00-bbe1-11eb-9cd5-ee89c3bd870b.png)
3Dモデルの原点は中央とは限らないですが、AABB::setPos()で設定する座標は中心点となっているため、
座標を合わせにくいです。
※size/2+posなどとしてオフセットすれば合わせられない事もないのですが。。

図は青がAABB::draw()、白が3Dモデルの描画位置です。
※この3Dモデルは原点が下の図の位置になっています。
![image](https://user-images.githubusercontent.com/43272572/119251621-73848600-bbe2-11eb-85c8-56f9e088fdd7.png)

**Comment by Reputeless** [comment]
`Rect` のようにオーバーロードを増やすことを検討します。

**Comment by itakawa** [comment]
関連して、AABBよりもOBBがCenter固定されている方が都合よくないかもしれません。
回転するときは原点を中心に回転する使い方が多いと思います。

**Comment by Reputeless** [comment]
v0.6 で
`Box` (AABB), `OrientedBox` (OBB) のコンストラクタに、中心座標ではなく底面中心座標を渡すオーバーロードを追加しました。
また、2 点から `Box` を作成する関数 `Box Box::FromTwoPoints(const Vec3& a, const Vec3& b)` を追加しました。
他にアイデアがあればお知らせください。

**Comment by itakawa** [comment]
ありがとうございます。
3Dのキャラクターは大抵足元がRootになっているのでAABBを合わせるには都合が良いと思います。

OBBは、回転があるので、実装会の時はrotatedAt()と、思いつきを言いましたが、2Dならともかく、
3Dでは意味がありませんでした。

今は、座標変換の行列を渡して、メッシュに合わせるのが良さそうと思うので、テストしています。
three.jsのOBBに、applyMatrix4という関数を見つけましたが、名前も機能もまさしく欲しいものでした。
[OBB.applyMatrix4](https://threejs.org/docs/#examples/en/math/OBB.applyMatrix4)

**Comment by Reputeless** [comment]
まさにそのような関数を先週実装したところです！

- `Geometry3D::TransformBoundingSphere(Sphere, Mat4x4)`
- `Geometry3D::TransformBoundingBox(Box, Mat4x4)`
- `Geometry3D::TransformBoundingOrientedBox(OrientedBox, Mat4x4)`
