### ISSUE TITLE
PPM 画像、一部の形式で encode/decode に失敗

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#591]
- reported by: https://twitter.com/majimenaakkun/status/1397081855497625602
- OpenSiv3D v0.4.3, および同じコードを利用している現在の v0.6 で、P4 形式の encode, P6 形式の decode に問題がありそう。要修正

オリジナルのコード作者の @agehama さん、対応可能でしょうか？

```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6

void Main()
{
	Window::Resize(1600, 800);

	Image image{ U"example/windmill.png" };
	image.savePPM(U"P1.ppm", PPMType::P1);
	image.savePPM(U"P2.ppm", PPMType::P2);
	image.savePPM(U"P3.ppm", PPMType::P3);
	image.savePPM(U"P4.ppm", PPMType::P4);
	image.savePPM(U"P5.ppm", PPMType::P5);
	image.savePPM(U"P6.ppm", PPMType::P6);

	Texture texture1{ U"P1.ppm" };
	Texture texture2{ U"P2.ppm" };
	Texture texture3{ U"P3.ppm" };
	Texture texture4{ U"P4.ppm" };
	Texture texture5{ U"P5.ppm" };
	Texture texture6{ U"P6.ppm" };

	while (System::Update())
	{
		texture1.draw(0,0);
		texture2.draw(480, 0);
		texture3.draw(960, 0);
		texture4.draw(0,360);
		texture5.draw(480, 360);
		texture6.draw(960, 360);
	}
}
```

**Comment by Reputeless** [comment]
僕が @agehama さんのオリジナルコードを移植する過程でミスった可能性が高いですね 😂

**Comment by agehama** [comment]
見てみます

**Comment by agehama** [comment]
どちらも最初のコードからあったミスでした。。

- P4 の encode の失敗
  - 画像の幅が8ピクセルの倍数の時に P4 の encode で余計なデータを出力してしまう
- P6 の decode 失敗
  - decode 時のヘッダとピクセルデータの間のホワイトスペースをスキップする処理で、最初のピクセル色がホワイトスペースに一致する値だったときピクセルデータも間違ってスキップしてしまう

修正はどのブランチから行えばよいでしょうか？

**Comment by Reputeless** [comment]
了解です。早速の対応ありがとうございます。
コミットメッセージに #591 を含め、`v6_winmac_develop` に Pull-request をお願いします。

**Comment by Reputeless** [comment]
開発中の v0.6 で修正されました。Thanks @agehama !
