### ISSUE TITLE
Color::gamma()で正しい値が取得できない

### ISSUE THREAD

**Issue by Ryoga-exe** [Siv3D/OpenSiv3D#595]
## 起こっている不具合

`Color::gamma()`で正しくガンマ値を適用した色が取得できません。
また、`ColorF::gamma()`と取得できる色が誤差とは考えられないほど異なり、また恐らく、こちらの方が正しく適用した色が取得できると考えられます。

サンプルコード

```cpp

Color col(35, 63, 168);
Print << col;
Print << col.gamma(2.0);
Print << ColorF(col).gamma(2.0);

while (System::Update())
{
	
	Rect(300, 300).draw(Arg::top = col, Arg::bottom = col.gamma(2.0));
	
	Rect(400, 0, 300, 300).draw(Arg::top = col, Arg::bottom = ColorF(col).gamma(2.0));
}

```

## 不具合を確認した環境等

`v0.4.3` 及び `v0.6`(winmac_develop) で確認しました。

OSはWindowsです。

**Comment by Reputeless** [comment]
ご報告 & 修正コミットありがとうございました！
