### ISSUE TITLE
Print()関数で使用できない関数がある。

### ISSUE THREAD

**Issue by Pine778** [Siv3D/OpenSiv3D#603]
Boostライブラリ（バージョン：1_75_0）の多倍長整数型
（boost::multiprecision::cpp_int）の変数を
Print()関数で画面に表示しようとすると
コンパイルエラーが起きます。

環境：・Windows10、
　　　・Boostライブラリ（バージョン：1_75_0）
　　　・Microsoft Visual Studio Community 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278

**Comment by Reputeless** [comment]
以下のような `Formatter()` を追加してください。
もしくは OpenSiv3D の BigInt 型を使ってください (cpp_int と同じです)。
```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.4.3
# include <boost/multiprecision/cpp_int.hpp>

namespace s3d
{
	inline void Formatter(FormatData& formatData, const boost::multiprecision::cpp_int& value)
	{
		formatData.string += Unicode::Widen(value.str());
	}
}

void Main()
{
	boost::multiprecision::cpp_int n = 123;

	Print << n;

	BigInt b = 1000;

	Print << b;

	while (System::Update())
	{

	}
}
```
