### ISSUE TITLE
Siv3D くんの 3D モデル追加

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#621]
https://github.com/itakawa/siv3dkun

**Comment by Reputeless** [comment]
現在、追加するファイルの内容を確認中です。

**Comment by Reputeless** [comment]
モデルは Siv3DKun2_Standing.obj を使います。
1. 首に＋マークが入ってる
![image](https://user-images.githubusercontent.com/3108136/126903495-fdd3af47-f62c-4589-ad45-1783a1b1acbf.png)

2. メッシュに裂け目がある
![image](https://user-images.githubusercontent.com/3108136/126903538-b6a9a329-ac3e-48ff-af0d-c033026dd268.png)

以上 2 点の修正をお願いします。

**Comment by Reputeless** [comment]
今後の ToDo

## 1.

- モデル修正

## 2.

- ファイルのリネーム。全部小文字にします。
  -  Siv3DKun2_Standing.obj → siv3d-kun.obj
  - siv3d-kun.mtl
  - eye.png
  - siv3d-kun.png
  - tools.png

## 3. クレジット表記

ファイルに同梱するテキストファイルに記載します。
例: https://github.com/Siv3D/OpenSiv3D/blob/v6_winmac_develop/WindowsDesktop/App/example/spritesheet/siv3d-kun-16.txt

- 作者名
-（オプション）作者のメールアドレスまたは URL
-（オプション）利用者へのコメント

**Comment by itakawa** [comment]
Siv3DKun2_Standing.objを修正しました。
確認おねがいします。
https://github.com/itakawa/siv3dkun

**Comment by Reputeless** [comment]
2 点の修正を確認しました。ありがとうございます。
すみませんが、もう 2 点お願いします。
・モデルの一部の Y 座標が地面より下になっているので 0 に合わせてください
![image](https://user-images.githubusercontent.com/3108136/127322917-cbc08a14-d520-43ee-ad0b-a3be50313b5f.png)

・Siv3D くんの髪を、眉と同じ色（グレー）にしてください
![image](https://user-images.githubusercontent.com/3108136/127322972-13870730-b346-4f25-8b69-86047c20c29f.png)

**Comment by itakawa** [comment]
・髪の毛の色の修正
・接地点の修正                      ※ぴったり0だと問題あるかもしれないので、少し浮かせています。
・見えないメッシュの削除　※つるはし(Tools.pngの削除)、口の内部
・テクスチャの更新               ※ズボンの明るさ、顔の+マークの改善(若干大きくなっています。)
・左足首の傾きを修正
を行いました。
[Siv3DKun2.obj.zip](https://github.com/Siv3D/OpenSiv3D/files/6900538/Siv3DKun2.obj.zip)

**Comment by Reputeless** [comment]
いろいろありがとうございます！
確認して再度連絡します。

**Comment by itakawa** [comment]
細かく指摘いただいて、ありがとうございます。
配信したことがないと、感覚的にあまいところがでてしまいました。
他にもありましたらお願いします。

**Comment by Reputeless** [comment]
モデルデータ確認完了です！
OpenSiv3D の規則に合うよう、ファイルのリネームと PNG 画像の限界までの圧縮を施した、コミット用の 4 個のファイルをこちらに用意しました。
- [siv3d-kun.zip](https://github.com/Siv3D/OpenSiv3D/files/6906124/siv3d-kun.zip)

① この 4 ファイルを [`v6_winmac_develop`](https://github.com/Siv3D/OpenSiv3D/tree/v6_winmac_develop) ブランチの

- `OpenSiv3D/WindowsDesktop/App/example/obj/`
- `OpenSiv3D/Linux/App/example/obj/`
- `OpenSiv3D/macOS/App/example/obj/`
- `OpenSiv3D/Web/App/example/obj/`

にそれぞれ追加（合計 16 ファイルの追加）をする Pull-request をお願いします。
★ `exmaple/obj/` フォルダに直接 4 ファイルを投入します。新しいフォルダは作成しません。

② `example/obj/credit.txt` に記載する、モデル作者のクレジット表記をお知らせください。
一番シンプルな場合だと

```
[siv3d-kun.obj]
https://github.com/itakawa/siv3dkun
```

になります。名前や別の URL を表示することも可能です。

以上 2 点よろしくお願いします。（実装会のときでも OK です）
