### ISSUE TITLE
Resourcesの容量を減らすのを簡単にしたい

### ISSUE THREAD

**Issue by Fuyutsubaki** [Siv3D/OpenSiv3D#638]
(特にWeb版で)生成物の容量を減らしたい。その際、resourcesの中身の比重が今のところ大きい

resourcesの中身について、現在はそれが自分にとって必要なのか不必要なのか、それともエンジンの制約上どうやっても消せないのか、OpenSiv3Dのソースから該当箇所を探してみる必要がある。わかりやすくすることで削減しやすくしたい

**Comment by Reputeless** [comment]
これに関する資料を、新チュートリアル「アプリの公開」にまとめました。
https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-release

**Comment by Reputeless** [comment]
Web 版のサイズ削減は今後ビルドオプション等でも対応していきたいと思っています。

**Comment by Reputeless** [comment]
v0.6.3 で

- Script 関連のライブラリの分離（オプトアウト方式）
- 必須フォントの削減
  - #682
  - #684
- シェーダファイルのサイズ節約
  - #687 

などの対応をしました。Web 版には Web v0.6.0b5 以降で反映される見込みです。
最終出力は最小で 1 桁 MB 程度にできると思います。
