### ISSUE TITLE
シングルタッチの挙動がv0.4.3とv0.6.0で異なる

### ISSUE THREAD

**Issue by KondoA9** [Siv3D/OpenSiv3D#645]
早速v0.6.0を使わせていただいております。
Surface Book 2でシングルタッチ時の挙動がv0.4.3と異なり、仕様なのかバグなのか判断ができないため一応報告させていただきます。

v0.4.3ではシングルタッチ時即座に`MouseL.down()`が呼ばれていたのですが、v0.6.0では
- ダブルタップ
- タッチして少し動かす

をしないとクリック判定にならないようです。

**環境**
- Surface Book 2
- Windows 10
- OpenSiv3D v0.4.3, v0.6.0

**再現コード**
```c++
# include <Siv3D.hpp>

void Main() {
    while (System::Update()) {
        if (MouseL.down()) {
            Print << U"Down";
        }
    }
}
```

**Comment by Reputeless** [comment]
ご報告ありがとうございます。調査します。

**Comment by Reputeless** [comment]
v0.6.0 のバグでした。修正が完了し、v0.4.3 のように動作するようになりました。
早ければ明日にも、本件含むいくつかのバグフィックスをした v0.6.1 をリリースします。
ご報告ありがとうございました。
