### ISSUE TITLE
Math に Tau 系の定数が欲しい

### ISSUE THREAD

**Issue by discosaan** [Siv3D/OpenSiv3D#673]
`Math` 名前空間の `Pi` 系の定数に加えて、 `Tau` 系の定数を追加してほしいです。

定数 τ は半径に対する円周の比で、2π と等しいです。
弧度法ではちょうど一周の角度を表せるという利点があり、私は π よりも τ を好んでいます。
標準で τ を使えるプログラミング言語もあります。

`Tau` `HalfTau` `InvTau` など、追加していただけると助かります。

参考:
[Wikipedia](https://ja.wikipedia.org/wiki/%CE%A4_(%E6%95%B0%E5%AD%A6%E5%AE%9A%E6%95%B0))
[ニコニコ大百科](https://dic.nicovideo.jp/a/%CF%84%28%E6%95%B0%E5%AD%A6%E5%AE%9A%E6%95%B0%29)

**Comment by Reputeless** [comment]
開発中の v0.6.3 に実装されました。提案ありがとうございました。
