### ISSUE TITLE
UnionFind (Disjoint Set Union)

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#742]

**Comment by polyester-CTRL** [comment]
https://twitter.com/chokudai/status/1310117095468797953?s=20&t=xDoygOaS6Rn_xFBwinB4_Q
学術的には「Disjoint Set Union」のほうが通じやすいらしいので、クラス名もDisjoint Set UnionもしくはDSUにしたほうがいいのではないでしょうか？

**Comment by polyester-CTRL** [comment]
グラフを連結成分に分け、その情報を返すメソッド「groups」があると便利だと思います。

参考資料
- https://atcoder.github.io/ac-library/master/document_ja/dsu.html
- https://qiita.com/R_olldIce/items/93b8f13e0d33da4ac331#3-%E4%BD%BF%E7%94%A8%E4%BE%8B


実装例
- https://github.com/atcoder/ac-library/blob/master/atcoder/dsu.hpp#L47

**Comment by Reputeless** [comment]
ご提案ありがとうございます。
調査・検討します。

**Comment by Reputeless** [comment]
- 様々なライブラリや資料の事例に基づき、`UnionFind` クラスを `DisjointSet` に変更しました。
- グループの個数を数える `DisjointSet::countSets()` を実装しました

AC-Library の `group()` 関数に相当する操作はあまりにも汎用的であり、
要素数が大きく、かつ union の少ない `DisjointSet` で乱用されるとメモリ消費が非効率であるため、Siv3D では提供しないことにしました。
