### ISSUE TITLE
GCC 11.1.0 以降において cpptoml でコンパイルエラーが出る

### ISSUE THREAD

**Issue by yaito3014** [Siv3D/OpenSiv3D#746]
GCC 11.1.0 以降における [いくつかのヘッダにおいて `<limits>` がインクルードされなくなった変更](https://github.com/gcc-mirror/gcc/commit/9af65c2b9047168f14e623d55f87beda33ba1503) により cpptoml のコンパイルが通らなくなっている。 ( cpptoml の [該当 issue](https://github.com/skystrife/cpptoml/issues/126) )

**Comment by yaito3014** [comment]
GCC 9.3.0 以降のサポートは今の所無いということで一旦クローズします。

**Comment by Reputeless** [comment]
v0.6.4 で修正しました！ ご報告ありがとうございます。
