### ISSUE TITLE
SceneManagerはコピー不可にすべき

### ISSUE THREAD

**Issue by m4saka** [Siv3D/OpenSiv3D#750]
`SceneManager`は現状コピー・ムーブ可能となっていますが、コピー・ムーブ不可にすべきと思われます。

ゲームを作成していた際に`SceneManager`の生成処理をMain関数から別関数に切り分けたところ、NRVOが効かない状況下(Debugビルド)でのみダングリングポインタが発生し、実行時エラーを引き起こすようでした。

下記が再現可能なコードです。

```cpp
#include <Siv3D.hpp> // OpenSiv3D v0.6.3

using MyApp = SceneManager<StringView>;

// Enterキーを押すとTestScene1とTestScene2を行き来するだけのシーン

class TestScene1 : public MyApp::Scene
{
public:
	explicit TestScene1(const InitData& initData)
		: MyApp::Scene(initData)
	{
		Print << U"TestScene1";
	}

	virtual void update() override
	{
		if (KeyEnter.down())
		{
			changeScene(U"TestScene2");
		}
	}
};

class TestScene2 : public MyApp::Scene
{
public:
	explicit TestScene2(const InitData& initData)
		: MyApp::Scene(initData)
	{
		Print << U"TestScene2";
	}

	virtual void update() override
	{
		if (KeyEnter.down())
		{
			changeScene(U"TestScene1");
		}
	}
};

MyApp MakeSceneManager()
{
	MyApp manager;
	manager.add<TestScene1>(U"TestScene1");
	manager.add<TestScene2>(U"TestScene2");
	return manager;
}

void Main()
{
	MyApp manager = MakeSceneManager();
	while (System::Update())
	{
		if (!manager.update())
		{
			break;
		}
	}
}
```

VS2022 Debugビルドにて上記を実行してEnterキーを押すと、アクセス違反による未定義動作に起因して下記のエラーが出ます(無視するとその後の処理でクラッシュ)。

![image](https://user-images.githubusercontent.com/14288724/159168627-f800427a-0e3d-433f-822e-2d5912ba0763.png)

`MakeSceneManager()`からの返却の際に`SceneManager`のムーブコンストラクタ(またはコピーコンストラクタ)が呼ばれた場合、Main関数では`SceneManager`の実体は元のものとは別物になります(※Debugビルドのみ)。

しかし、その後もシーン生成に使用される`InitData`内のポインタが更新されないため、`IScene::m_manager`が指すのはムーブ(コピー)元の実体のままとなり、シーン内で`IScene::changeScene()`を呼ぶと解放済みの実体が参照されて未定義動作を引き起こします。

下記のように`SceneManager`をコピー(およびムーブ)不可にすればコンパイルエラーにできると思いますので、ご検討をお願いします。
https://github.com/m4saka/OpenSiv3D/commit/a4bd705df1a2757ae0a1c91269c54c9fc07666ee

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
調査します。

**Comment by Reputeless** [comment]
`SceneManager` に、現在アクティブなシーンマネージャーのポインタを保持するメンバ変数を追加し、
`InitData` 内では、親となる `SceneManager` を間接的に指すようにすることで、ご報告いただいた問題を解決しました。

該当コミット:
- https://github.com/Siv3D/OpenSiv3D/commit/10b3dbad880e3464c333e245ccb6e2bff597d7f8#

本修正により、`SceneManager` に対してムーブコンストラクタ、ムーブ代入を安全に利用できるようになりました。
また、`SceneManager` のコピーコンストラクタ、コピー代入は deleted されました。

v0.6.4 から本変更が適用されます。ご報告ありがとうございました。
本 Issue は v0.6.4 リリース時に close されます。

**Comment by m4saka** [comment]
ムーブできる形にしていただいたおかげでSceneManager生成の関数分けができてとても助かります！
調査・修正いただきありがとうございました！！
