### ISSUE TITLE
WaveSample / WaveSampleS16 変換が不統一

### ISSUE THREAD

**Issue by NachiaVivias** [Siv3D/OpenSiv3D#795]
### 問題のソースコード

このソースコードは、音声ファイルを何も変更せずに保存しなおしているように見えますが、実は a.wav に保存された任意の波形を 0 の列に書きかえます。（もしかすると環境依存かもしれません）

```c++
# include <Siv3D.hpp> // OpenSiv3D v0.6.2

void Main()
{
	WAVEDecoder decoder;
	Wave wave;
	for (int i = 0; i < 32768; i++) {
		wave = decoder.decode(U"a.wav");
		wave.saveWAVE(U"a.wav");
	}
}
```

### 原因と思われる部分

ファイルを読んで書く過程で int16 -> float -> int16 の変換が行われます。

https://github.com/Siv3D/OpenSiv3D/blob/43814fa861fd3862ee0b9ea0652540fd548eb928/Siv3D/include/Siv3D/detail/WaveSample.ipp#L62-L65

https://github.com/Siv3D/OpenSiv3D/blob/43814fa861fd3862ee0b9ea0652540fd548eb928/Siv3D/include/Siv3D/detail/WaveSample.ipp#L173-L176

clamp を無視すると 32768 で割って 32767 を掛けているため絶対値がわずかに減り、整数へ変換するとはじめより 0 に近い整数に変換されます。

**Comment by NachiaVivias** [comment]
書き上げる前に誤って投稿してしまっていました。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。確かにそうですね！
`* 32767` を `* 32768` にしたほうが良さそうです。

### よりシンプルな検証プログラム
```cpp
# include <Siv3D.hpp>

void Main()
{
	WaveSample sampleFloat{ 1.0f, 1.0f };
	Console << sampleFloat.left << U" " << sampleFloat.right;

	for (int i = 0; i < 10; ++i)
	{
		Console << U"---";
		WaveSampleS16 sampleS16 = sampleFloat.asWaveSampleS16();
		sampleFloat = sampleS16.asWaveSample();

		Console << sampleS16.left << U" " << sampleS16.right;
		Console << sampleFloat.left << U" " << sampleFloat.right;
	}

	while (System::Update())
	{

	}
}
```

### 修正箇所
全部で 4 箇所の `* 32767` があります。
もし興味があれば `v6_devlop` ブランチをフォークし、以下の 4 箇所を修正したコミットを Pull-request で `v6_develop` ブランチへ送ってください。

https://github.com/Siv3D/OpenSiv3D/blob/e4ef5d9676f0048b3ce527779baaff3ad0d3059b/Siv3D/include/Siv3D/detail/WaveSample.ipp#L59-L64

https://github.com/Siv3D/OpenSiv3D/blob/e4ef5d9676f0048b3ce527779baaff3ad0d3059b/Siv3D/src/Siv3D/AudioFormat/WAVE/WAVEEncoder.cpp#L32

面倒であればこちらで全部対応します。
明日中に送っていただければ、今週リリースの v0.6.4 にマージしてリリースされます。
