### ISSUE TITLE
[実行時エラー] macOS,Linuxの`FileSystem::SelectFolder()`、macOSの`FileSystem::FullPath()`の結果が不自然

### ISSUE THREAD

**Issue by KondoA9** [Siv3D/OpenSiv3D#824]
関連する問題かと思うので同じIssueにまとめました。

**エラーの内容 | Describe the runtime error**

1. `FileSystem::SelectFolder()`で得たパスの末尾がWindowsでは`/`を含み、macOS, Linuxでは`/`を含まない
2. macOSにおいて、`FileSystem::FullPath()`の引数に`/Users/`以外（`/usr/`, `/Applications/`等）のフォルダ（サブフォルダも含む）を渡すと、`{カレントディレクトリ}/Applicatios`のようになる
   - 相対パスとして処理される
   - 末尾に`/`がつかない

**再現方法 | To Reproduce**

```c++
# include <Siv3D.hpp> // OpenSiv3D v0.6.4

void Main()
{
  Print << FileSystem::FullPath(U"/usr");
  while (System::Update()) {
    if (KeyEnter.down()) {
      if (const auto folder = Dialog::SelectFolder(); folder.has_value()) {
        Print << folder.value();
        Print << FileSystem::FullPath(folder.value());
      }
    }
  }
}
```

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows11 22H2, macOS Monterey 12.4, Ubuntu-20.04 LTS

**備考 | Additional context**

1. `FileSystem::SelectFolder()`で得たパスの末尾がWindowsでは`/`を含み、macOS, Linuxでは`/`を含まない<br>
SivDialog_Windows.cppでは`FileSystem::SelectFolder()`の最後に`FileSystem::FullPath()`を呼んでいますが、SivDialog_macOS.mm、SivDialog_Linux.cppでは呼んでいないのでこれが原因かと思います。

2. macOSにおいて、`FileSystem::FullPath()`の引数に`/Users/`以外（`/usr/`, `/Applications/`等）のフォルダ（サブフォルダも含む）を渡すと、`{カレントディレクトリ}/Applicatios`のようになる<br>
  SivDialog_macOS.mmの`FileSystem::FullPath()`で`/Users/`以外を相対パスで処理するようにしているためかと思います。（具体的な解決策はわかりませんでしたが。。。）
  https://github.com/Siv3D/OpenSiv3D/blob/72acbf62e661698f19d583059c148daf5b0635f2/Siv3D/src/Siv3D-Platform/macOS/Siv3D/FileSystem/SivFileSystem_macOS.mm#L446-L454

**Comment by Reputeless** [comment]
開発中の v0.6.5 でいずれの問題も修正しました！
ご報告ありがとうございました。
