### ISSUE TITLE
`FilePath`を結合する関数の提案

### ISSUE THREAD

**Issue by KondoA9** [Siv3D/OpenSiv3D#825]
**追加する機能の内容 | Describe the solution you'd like**
- Pythonの[`os.path.join()`](https://docs.python.org/ja/3/library/os.path.html#os.path.join)ライクなパス結合関数
- `<filesystem>`の`std::filesystem::path operator/(std::filesystem::path, std::filesystem::path)`のような演算子
  `using FilePath = String`なので難しいかもしれませんが

例
```c++
FilePath path1, path2;
FilePath combined1 = FileSystem::Join(path1, path2);
FilePath combined2 = path1 / path2;
```

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
現状ではパスの結合をしようと思うと`path1 + path2 + ...`というように書くことになると思います。
この場合、スラッシュが含まれているかどうかを逐一確認しなければならず、`path1 + U"/" + path2 + path3`のように冗長な形になってしまうこともあります。
また、関数を用いることで明示的にパスの結合ができるので見通しが良くなると思います。

Python以外にも、JavaScriptの[`path.join()`](https://nodejs.org/api/path.html#pathjoinpaths)やC#の[`Path.Join()`](https://docs.microsoft.com/ja-jp/dotnet/api/system.io.path.join?view=net-6.0), [`Path.Combine()`](https://docs.microsoft.com/ja-jp/dotnet/api/system.io.path.combine?view=net-6.0)等他の言語ではメジャーでとても便利な関数なので是非検討よろしくお願いします。

**Comment by Reputeless** [comment]
ご提案ありがとうございます。これは必要な関数です。v0.6.5 で実装します。

**Comment by Reputeless** [comment]
開発中の v0.6.5 に `FileSystem::PathAppend(FilePathView lhs, FilePathView rhs)` を実装しました。
ご提案ありがとうございました。

サンプル
```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6.5

void Test(FilePathView a, FilePathView b)
{
	if (a == b)
	{
		Console << U"[OK]";
	}
	else
	{
		Console << U"[Failed]: " << a << U" vs " << b;
	}
}

void Main()
{
	Test(FileSystem::PathAppend(U"example", U"windmill.png"), U"example/windmill.png");
	Test(FileSystem::PathAppend(U"example/", U"windmill.png"), U"example/windmill.png");
	Test(FileSystem::PathAppend(U"./example", U"windmill.png"), U"./example/windmill.png");
	Test(FileSystem::PathAppend(U"./App/", U"example/windmill.png"), U"./App/example/windmill.png");
	Test(FileSystem::PathAppend(U"./", U"windmill.png"), U"./windmill.png");

	Test(FileSystem::PathAppend(U"example", U""), U"example/");
	Test(FileSystem::PathAppend(U"example/", U""), U"example/");
	Test(FileSystem::PathAppend(U"./example", U""), U"./example/");
	Test(FileSystem::PathAppend(U"./example/", U""), U"./example/");

	Test(FileSystem::PathAppend(U"", U"windmill.png"), U"windmill.png");
	Test(FileSystem::PathAppend(U"", U"example"), U"example");
	Test(FileSystem::PathAppend(U"", U"example/"), U"example/");
	Test(FileSystem::PathAppend(U"", U"./example/"), U"./example/");

	Test(FileSystem::PathAppend(U"", U""), U"");

# if SIV3D_PLATFORM(WINDOWS)
	Test(FileSystem::PathAppend(U"C:foo", U"bar"), U"C:foo/bar");
	Test(FileSystem::PathAppend(U"C:/foo/", U"bar"), U"C:/foo/bar");
# endif

	while (System::Update())
	{

	}
}
```
