### ISSUE TITLE
HLSL や GLSL のメンバ関数の引数の型が FilePathView ではない

### ISSUE THREAD

**Issue by Ryoga-exe** [Siv3D/OpenSiv3D#833]
[ShaderCommon.hpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/Siv3D/ShaderCommon.hpp) で定義されている `HLSL`, `GLSL`, `MSL`, `ESSL`, `WGSL` のコンストラクタの引数 `_path` の型が、`FilePathView` ではなく、`FilePath` になっています。

また `MSL` では、引数 `_entryPoint` の型が `StringView` なのに対し、`HLSL` では `String` です。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
これらのコンストラクタ引数は `FilePath` や `String` にしたうえで、次のようにムーブで `String` 型のメンバ変数に割り当てるのが好ましいパターンです。（詳しく知りたい場合は『Effective Modern C++』の項目 27, 項目 41 を読んでみてください）
```cpp
inline HLSL::HLSL(FilePath _path)
	: path{ std::move(_path) } {}
```

View を使うと
```cpp
FilePath GetPath();
HLSL hlsl{ GetPath() };
```
のようなコードで `GetPath()` の戻り値をムーブできず非効率になります。

したがって、これらのクラスのコンストラクタ引数は View にする必要はないのですが、現状のコードでは `std::move()` をしておらず、結果として効率の良いコードになっていませんでした。v0.6.5 で修正したいと思います。

**Comment by Reputeless** [comment]
#835 に引き継いでこちらは close します。

**Comment by Ryoga-exe** [comment]
なるほど...非効率になってしまうのですね。なんとなく理解しました、ありがとうございます。
