### ISSUE TITLE
Grid::choiceを呼び出すビルドが失敗する

### ISSUE THREAD

**Issue by falrnd** [Siv3D/OpenSiv3D#840]
**エラーの内容 | Describe the build error**
Grid::choiceを呼び出すビルドが失敗する

エラー	C2679	二項演算子 '-': 型 'int' の右オペランドを扱う演算子が見つかりません (または変換できません)。	Siv3D-Test	(略)\OpenSiv3D\Siv3D\include\Siv3D\detail\Grid.ipp	700	
エラー	C2440	'return': 'int *' から 'int &' に変換できません。	Siv3D-Test	(略)\OpenSiv3D\Siv3D\include\Siv3D\detail\Grid.ipp	702	

**再現方法 | To Reproduce**
```C++
# include <Siv3D.hpp> // OpenSiv3D v0.6.4

void Main()
{
	Grid<int> g{ 10,10 };
	g.choice();
}
```

**ビルド環境 | Develop environment (please complete the following information):**
 - OS: Windows 11
 - 開発環境 | IDE: Microsoft Visual Studio Community 2022 

**備考 | Additional context**

**Comment by Reputeless** [comment]
Good catch!
修正します。
