### ISSUE TITLE
JSON のバイナリ対応

### ISSUE THREAD

**Issue by TwoSquirrels** [Siv3D/OpenSiv3D#842]
**追加する機能の内容 | Describe the solution you'd like**

JSON クラスを BSON, CBOR, MessagePack のデータ形式に/から変換できる

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**

JSON データをバイナリー形式で保存/読み込みできない

**備考 | Additional context**

[nlohmann/json の機能](https://github.com/nlohmann/json#binary-formats-bson-cbor-messagepack-ubjson-and-bjdata)

**Comment by Reputeless** [comment]
v0.6.5 での対応に向け実装を進めます。ご提案ありがとうございます。

**Comment by Reputeless** [comment]
開発中の v0.6.5 で実装完了しました。
ご提案ありがとうございました！
