### ISSUE TITLE
[実行時エラー] RoundRectの枠の描画が破綻する

### ISSUE THREAD

**Issue by sthairno** [Siv3D/OpenSiv3D#856]
**エラーの内容 | Describe the runtime error**

RoundRectの内側の線を描画する際、半径が枠の太さを下回ると描画が破綻します。

gifはHTMLとSiv3Dで同じ挙動をするテストコードを作成し、比較した動画です。
使用したテストコードは`再現方法 | To Reproduce`にあります。

**半径 > 枠太さ**
![rrect1](https://user-images.githubusercontent.com/45668272/181871533-b42d578a-982b-4e9f-8826-a1e97a4f3b06.gif)

**半径 < 枠太さ**
![rrect2](https://user-images.githubusercontent.com/45668272/181871535-4288083d-93db-4d42-a776-d8b851537b09.gif)

**再現方法 | To Reproduce**

**HTML**
https://jsfiddle.net/23Lnzq7x/12/

**Siv3D**
```cpp
#include <Siv3D.hpp> // OpenSiv3D v0.6.4

void Main()
{
	Scene::SetBackground(ColorF(0.9));

	double frameThickness = 0;
	double roundSize = 0;

	while (System::Update())
	{
		SimpleGUI::Slider(frameThickness, 0.0, 100.0, { 5, 5 }, 200.0);
		SimpleGUI::Slider(roundSize, 0.0, 100.0, { 5, 45 }, 200.0);

		RoundRect rrect(5, 85, 100 + frameThickness * 2, 100 + frameThickness * 2, roundSize);
		rrect.drawFrame(frameThickness, 0, Palette::Black);
	}
}
```

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 11
 - バージョン | Version: OpenSiv3D v0.6.4
 - GPU: NVIDIA GeForce RTX 3070
 - ブラウザ (Web 版) | Browser: Firefox

**備考 | Additional context**

**Comment by Reputeless** [comment]
開発中の v0.6.5 で、Rect / RoundRect / RoundRectF の drawFrame() にどのような値を渡しても異常な結果が表示されないよう修正しました。ご報告ありがとうございます！
