### ISSUE TITLE
[ビルドエラー] Siv3D.hppをincludeするとそれ以降の`NULL`が空文字列に置換される

### ISSUE THREAD

**Issue by ROCKTAKEY** [Siv3D/OpenSiv3D#858]
**エラーの内容 | Describe the build error**
`#include<Siv3D.hpp>`以後の行で、NULLが空文字列に置換されてしまう（つまりNULLの部分になにも書いていないことになる）。
```
Siv3D/OpenSiv3D/Linux/App/Main.cpp: In function 'void Main()':
Siv3D/OpenSiv3D/Linux/App/Main.cpp:10:18: error: expected primary-expression before ';' token
   10 |     int *x = NULL;
      |                  ^
```
**再現方法 | To Reproduce**
以下のプログラムを`Main.cpp`として、[所定の方法（cmake）](https://github.com/Siv3D/OpenSiv3D/blob/main/.github/workflows/ci.yml#L62-L71)でビルドする
```c++
# include <Siv3D.hpp> // OpenSiv3D v0.6.4

void Main()
{
    int *x = NULL;
}
```
**ビルド環境 | Develop environment (please complete the following information):**
 - OS: GNU Guix System, Ubuntu20.04
 - 開発環境 | IDE: Emacs, gcc@9.4.0, cmake@3.16.3

**備考 | Additional context**
これにより、Siv3D以外のライブラリなど、`SIv3D.hpp`インクルード以後でNULLを使ったすべての部分がエラーを吐きます。
ライブラリが壊れてしまうワークアラウンドとしては、Siv3D.hppを一番最後にインクルードするというものがあります。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。原因箇所を特定できますか。

**Comment by ROCKTAKEY** [comment]
今しがた調査しました。

`ccls`(clangベースの言語サーバー)によって`NULL`の定義を辿っていったところ、まず標準の`stddef.h`にて
```C++
#if defined(__need_NULL)
#undef NULL
#ifdef __cplusplus
#  if !defined(__MINGW32__) && !defined(_MSC_VER)
#    define NULL __null /****************** See this line ********************/
#  else
#    define NULL 0
#  endif
#else
#  define NULL ((void*)0)
#endif
```
のように `#define NULL __null`していました。さらに辿ると、[`Siv3D/include/ThirdParty/DirectXMath/sal.h`](https://github.com/Siv3D/OpenSiv3D/blob/main/Siv3D/include/ThirdParty/DirectXMath/sal.h#L2603-L2606)において
```C++
#ifndef PAL_STDCPP_COMPAT
    #define __null  /********************* See this line ***********************/
    #define __notnull
#endif // !PAL_STDCPP_COMPAT
```
`#define __null`していました。

これにより、`NULL`は`__null`に置換されたあと` `（空文字列）に置換されていると考えられます。

**Comment by Reputeless** [comment]
開発中の v0.6.5 で修正しました。ご報告ありがとうございました！
