### ISSUE TITLE
文字列をパーセントエンコードする機能

### ISSUE THREAD

**Issue by mukade-daiou** [Siv3D/OpenSiv3D#864]
**追加する機能の内容 | Describe the solution you'd like**
Stringなどの文字列をパーセントエンコードする機能

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
SimpleHTTP::Saveなどでurlを指定する際にGUIや入力で受け取った日本語をurlに反映させることができるようになる。

**Comment by Reputeless** [comment]
ご提案ありがとうございます！
ライブラリ内部コードにそのような関数があったので、それを v0.6.5 で公開して対応できそうです。

**Comment by Reputeless** [comment]
開発中の v0.6.5 に実装しました。ご提案ありがとうございました。
