### ISSUE TITLE
v0.6.6 に向けた Script の API 追加

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#868]
- [x] `LicenseManager`
- [x] XInput
- [x] `Camera2DParameters`

**Comment by Kyle873** [comment]
XInput and related classes would be good to have for Gamepad support.

**Comment by Reputeless** [comment]
done (v0.6.6)

- Camera2DParameters: 4d8caa3
- LicenseManager: 8aaa41176
- XInput: 47d02f5
