### ISSUE TITLE
指定したURL/パスをデフォルトのアプリで開く

### ISSUE THREAD

**Issue by sthairno** [Siv3D/OpenSiv3D#888]
**追加する機能の内容 | Describe the solution you'd like**

指定されたURL/パスをOSに関連付けられたアプリで開きたいです。

このパスには

- 絶対パス
- 相対パス
- UNCパス (Windowsのみ)
- URIパス

を含みます。

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**

- エディタでのファイルの編集
- フォルダをエクスプローラーで開く
- OS設定(`ms-settings:`)やSteam(`steam:`)など、特殊なURIスキームを持つアプリを開く

といった動作がスムーズにできるようになります。

**備考 | Additional context**

Linuxでは`xdg-open`を使うことで実現可能です。
必要に応じてSystem::LaunchBrowserと統合しても良いかもしれません。

**Comment by Reputeless** [comment]
v0.6.8 での実装に向けて開発に着手しました。
