### ISSUE TITLE
PlayingCard::Packをデフォルト構築してジョーカーをdrawするとクラッシュ

### ISSUE THREAD

**Issue by falrnd** [Siv3D/OpenSiv3D#921]
**エラーの内容 | Describe the runtime error**
Application terminated due to a exception 'EXCEPTION_ACCESS_VIOLATION'

**再現方法 | To Reproduce**
```C++
# include <Siv3D.hpp> // OpenSiv3D v0.6.6

void Main()
{
	using PlayingCard::Suit;
	const auto pack = PlayingCard::Pack{};
	//const auto pack = PlayingCard::Pack{ 100.0 };
	const auto card = PlayingCard::CreateDeck(1);

	while (System::Update())
	{
		for (auto [i, c] : Indexed(card)) {
			Console << i;
			pack(c).drawAt(Scene::CenterF());
		}
	}
}
```

* 逆にジョーカー以外はクラッシュしない(恐らく)

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - バージョン | Version: 22H2

**Comment by Raclamusi** [comment]
Visual Studio で Debug ビルドした時のエラーの内容は次のようなものでした。

> Expression: vector subscript out of range

このことから、ジョーカーでのみクラッシュするのは [SivPlayingCard.cpp:183](https://github.com/Siv3D/OpenSiv3D/blob/f9d45c4f789f59673c254d8f90f526762f469dce/Siv3D/src/Siv3D/PlayingCard/SivPlayingCard.cpp#L183) で `vector` ( `Array` ) の範囲外参照が発生するためだと思います。

https://github.com/Siv3D/OpenSiv3D/blob/f9d45c4f789f59673c254d8f90f526762f469dce/Siv3D/src/Siv3D/PlayingCard/SivPlayingCard.cpp#L180-L183

`PlayingCard::CardInfo::draw(const s3d::Vec2&)` では、ジョーカーを描画する場合のみ <code>Font::getGlyph**s**</code> を使っていますが、このメンバ関数は取得に失敗した時に空の `Array` を返します。
しかし、そのメンバ関数を呼び出した次の行でチェックなしにその結果の 0 番目の要素にアクセスしているため、取得に失敗していた場合はここで未定義動作となります。

**Comment by Reputeless** [comment]
情報提供ありがとうございます。
クラッシュを回避 + デフォルト構築した `PlayingCard::Pack()` では無ではなく適当なサイズの白紙を表示するようにしました。
