### ISSUE TITLE
P2Bodyのangleの範囲を正規化したい

### ISSUE THREAD

**Issue by fafstar** [Siv3D/OpenSiv3D#927]
**追加する機能の内容 | Describe the solution you'd like**
P2Bodyの角度をgetAngleで取得する際に値を-pi~pi等にスケーリングします。

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
以下のような感じで回転させ続けると`body.getAngle()`の値が増え続ける問題が解決します。
```
P2Body body = world.createRect(P2Dynamic, pos, size);
body.setAngle(body.getAngle() + 0.01);
```

**備考 | Additional context**

**Comment by Reputeless** [comment]
開発中の v0.6.7 において `NormalizeAngle()` 関数を実装しました。
ご提案ありがとうございました。
