### ISSUE TITLE
HTTPResponseの内容がリダイレクト前のデータになる

### ISSUE THREAD

**Issue by sthairno** [Siv3D/OpenSiv3D#958]
**エラーの内容 | Describe the runtime error**

`SimpleHTTP::Get`や`SimpleHTTP::Post`はリダイレクト先を辿った先のデータを取得しますが、それぞれの戻り値であるHTTPResponseはリダイレクト前のデータになっています。

これにより指定したURLでリダイレクトが発生した場合、データ本文はリダイレクト先を受け取れているのに対し、HTTPResponseのステータスコードは301になるような問題が発生します。

**再現方法 | To Reproduce**

```cpp
# include <Siv3D.hpp> // OpenSiv3D v0.6.6

void Main()
{
	{
		// https://www.google.comへリダイレクト
		auto response = SimpleHTTP::Get(U"https://google.com", {}, U"response1.txt");
		Console << response.getStatusLine();

		// response -> "https://google.com"にアクセスした時のヘッダ情報 (301 Moved Permanently)
		// response1.txt -> "https://www.google.com"にアクセスした時のデータ
	}
	{
		// リダイレクトしない
		auto response = SimpleHTTP::Get(U"https://www.google.com", {}, U"response2.txt");
		Console << response.getStatusLine();

		// response -> "https://www.google.com"にアクセスした時のヘッダ情報 (200 OK)
		// response2.txt -> "https://www.google.com"にアクセスした時のデータ
	}

	while (System::Update())
	{ }
}
```

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS: Windows 10
 - バージョン | Version: 0.6.6
 - GPU: Intel Iris Plus Graphics 640

**備考 | Additional context**

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
コードの問題箇所 or 修正案があれば対応が早くなります。

**Comment by Reputeless** [comment]
SimpleHTTP の内部実装において、`std::string responseHeader` にリダイレクト前とリダイレクト後、両方のレスポンスが含まれていて、前者のみをパースしていたのが原因でした。v0.6.7 で修正予定です。

**Comment by Reputeless** [comment]
開発中の v0.6.7 で修正しました。ご報告ありがとうございました！
