### ISSUE TITLE
デューティー比を指定できる矩形波

### ISSUE THREAD

**Issue by voidproc** [Siv3D/OpenSiv3D#966]
Periodic名前空間の関数として、デューティー比を指定できる矩形波があると便利だと思います。

このような：
`double Pulse0_1(double periodSec, double dutyCycle, double t = Scene::Time()) noexcept;`

これにより例えば25%矩形波を `Pulse0_1(1s, 0.25)` などとして簡単に利用できるようになります。

実装例：
https://gist.github.com/voidproc/1c9f3122a590df6114593b6026353202

**Comment by Reputeless** [comment]
便利な関数です。
戻り値の説明は「0.0 または 1.0」「-1.0 または 1.0 」のようにしましょう。
pull-request を送っていただければマージします。
