### ISSUE TITLE
「fi」などの文字列の後の絵文字が正しく表示されないバグ

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/OpenSiv3D#971]
「fi」や「ff」、「fl」などの後に絵文字を含む文字列を `Font` や `Print` で描画するとき、その絵文字が正しく表示されません。

発生要因の文字列が「fi」などであることから、[リガチャ](https://ja.wikipedia.org/wiki/%E5%90%88%E5%AD%97)が関係していそうです。

**再現コード**
```c++
# include <Siv3D.hpp> // OpenSiv3D v0.6.7

void Main()
{
	Scene::SetBackground(ColorF{ 0.6, 0.8, 0.7 });

	const Font font{ FontMethod::MSDF, 48, Typeface::Bold };
	const Font emojiFont{ 48, Typeface::ColorEmoji };
	font.addFallback(emojiFont);

	Print << U"Hello,🦖! fi Hello,🦖!";

	while (System::Update())
	{
		font(U"Hello,🦖! fi Hello,🦖!").drawAt(64, Scene::Center(), ColorF{0.2, 0.4, 0.8});
	}
}
```

**実行結果**
![「fi」などの文字列の後の絵文字が正しく表示されない様子](https://user-images.githubusercontent.com/61970673/227302158-1c55e159-6f44-4b66-b7fe-84bb71196a94.png)

**備考**
https://siv3d.jp/bbs/patio.cgi?read=535&ukey=0 で Script においてこの問題が発生することが指摘されています。

**Comment by Raclamusi** [comment]
原因はフォールバックの際にリガチャによる**文字のインデックス**と **`GlyphCluster` のインデックス**のずれが考慮されていないことのようです。
以下のコードで `GlyphCluster` のインデックスを `StringView::substr` に渡しており、それによってリガチャが発生した場合に意図と異なる文字の `GlyphCluster` を取得することになっています。

https://github.com/Siv3D/OpenSiv3D/blob/f62a80040fb3f0fd1f647002bf6d41c4b1ca1f0d/Siv3D/src/Siv3D/Font/FontData.cpp#L189-L190

`hb_glyph_info_t::cluster` によって原文中の文字に対応するインデックスが分かるので、それによって `StringView::substr` を呼び出すように修正することが考えられます。

検証はまだですが、取り急ぎ。

**Comment by Raclamusi** [comment]
フォールバック処理における `StringView::substr` の引数を修正することで解決できそうです。
以下に修正案を示します。

**修正案 - Siv3D/src/Siv3D/Font/FontData.cpp**
```diff
+	size_t fallbackStrSize = ((count <= (i + k)) ? s.size() : glyphInfo.info[(i + k)].cluster) - pos;
+	
	bool fallbackDone = false;
	uint32 fallbackIndex = 1;
	
	for (const auto& fallbackFont : m_fallbackFonts)
	{
		if (fallbackFont.expired())
		{
			continue;
		}
	
		const Array<GlyphCluster> clustersB = 
-			SIV3D_ENGINE(Font)->getGlyphClusters(fallbackFont.lock()->id(), s.substr(i, k), false, ligature);
+			SIV3D_ENGINE(Font)->getGlyphClusters(fallbackFont.lock()->id(), s.substr(pos, fallbackStrSize), false, ligature);
	
		if (clustersB.none([](const GlyphCluster& g) { return (g.glyphIndex == 0); }))
		{
			for (size_t m = 0; m < clustersB.size(); ++m)
			{
				const auto& clusterB = clustersB[m];
				result << GlyphCluster{ clusterB.glyphIndex, fallbackIndex, pos };
			}
	
			fallbackDone = true;
			break;
		}
	
		++fallbackIndex;
	}
```

**実行結果**
![絵文字の表示が修正された実行画面](https://user-images.githubusercontent.com/61970673/227503310-be4a8dcd-4d48-4049-9499-408adedea91c.png)

**修正箇所**
https://github.com/Siv3D/OpenSiv3D/blob/f62a80040fb3f0fd1f647002bf6d41c4b1ca1f0d/Siv3D/src/Siv3D/Font/FontData.cpp#L179-L205

**Comment by Raclamusi** [comment]
この問題、リガチャが発生するケースのほかに、異体字セレクタが含まれる場合にも発生しますね。

**Comment by Reputeless** [comment]
ありがとうございます！ ご提案いただいた修正内容で解決することを確認しました。
`size_t fallbackStrSize =` の前に `const` を付け pull-request していただければマージします。
