### ISSUE TITLE
Timer::isRunnning() は 0 に達したとき false を返すべき？

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/OpenSiv3D#987]
要検討
- reported by: https://discord.com/channels/443310697397354506/998714158621147237/1091676374474965002

#### before
```cpp
bool Timer::isRunning() const noexcept
{
	return (m_isStarted && not m_pausing);
}
```

#### after
```cpp
bool Timer::isRunning() const noexcept
{
	return (m_isStarted && (not m_pausing) && (not reachedZero()));
}
```

**Comment by Reputeless** [comment]
d5efa570fab2c11f26613227b9bc314b6e4cfd19

**Comment by Raclamusi** [comment]
この変更が [Siv3DTest_Timer.cpp](https://github.com/Siv3D/OpenSiv3D/blob/main/Test/Siv3DTest_Timer.cpp) に反映されておらず、テストが落ちます。

**Comment by Reputeless** [comment]
Fixed. Thank you!
