### ISSUE TITLE
動き始めた時の低速の時に足場のP2Bodyと位置が重なる時に段差もないのに止まってしまう。

### ISSUE THREAD

**Issue by neva8492** [Siv3D/OpenSiv3D#993]
**エラーの内容 | Describe the runtime error**
動き始めた時の低速の時に足場のP2Bodyと位置が重なる時に段差もないのに止まってしまう。

**発生環境(デスクトップの場合) | Desktop (please complete the following information):**
 - OS:Windows
 - バージョン | Version:11

		# include <Siv3D.hpp> // OpenSiv3D v0.6.8

		void Main()
		{

		//Window::Resize(1920, 1080);

		// 重力加速度 (cm/s^2)
		const double gravity = 980;

		// 2D 物理演算のワールド
		P2World world{ gravity };

		// 2D 物理演算のシミュレーションステップ（秒）
		double stepSec = (1.0 / 200.0);

		// 2D 物理演算のシミュレーション蓄積時間（秒）
		double accumulatorSec = 0.0;

		P2Body body_player;
		Array<P2Body> body_block;

		//ブロックの位置
		Array<Vec2> pos_block{ 100 };

		//操作キャラ配置
		body_player = world.createRect(P2Dynamic, { 300 + 48 * 2 ,0 }, SizeF{ 48,48 }, P2Material{ .density = 0.3, .restitution = 0.0, .friction = 0.3 }, P2Filter{ .categoryBits = 1 ,.maskBits = 1 ,.groupIndex = 1 }).setFixedRotation(true);

		//グリッド状に配置
		for (size_t i = 0; i < 5; i++) {
			for (size_t i2 = 0; i2 < 5; i2++) {
				pos_block[i * 5 + i2] = { 48 * i2 + 300, 48 * i + 400 };
				body_block << world.createRect(P2Static, { pos_block[i * 5 + i2] }, { Vec2{48,48} }, P2Material{ .density = 0.3, .restitution = 0.0, .friction = 0.3 }, P2Filter{ .categoryBits = 1,.maskBits = 1 });
			}
		}
		while (System::Update())
		{

			// 2D 物理演算のワールドを更新
			for (accumulatorSec += Scene::DeltaTime(); stepSec <= accumulatorSec; accumulatorSec -= stepSec) {
				world.update(stepSec);
			}

			//操作
			if (KeyD.pressed())
			{
				body_player.applyForce({ 100,0 });
			}
			if (KeyA.pressed())
			{
				body_player.applyForce({ -100,0 });
			}

			//描画
			body_player.drawFrame();

			for (size_t i = 0; i < body_block.size(); i++) {
				body_block[i].drawFrame();
			}
		}

		}

**Comment by Reputeless** [comment]
物理シミュレーションで発生する一般的な現象です。
https://box2d.org/posts/2020/06/ghost-collisions/

これを避けるためには、（滑らかに移動したい）つながっている辺は 1 つの shape (LineString など) だけで構成されていなければなりません。
したがって、タイル状に shape を敷き詰めて地形を作るのは、物理シミュレーション的には不適です。

**Comment by neva8492** [comment]
ゴースト衝突というものがあるんですね。
余計な手間かけさせてすいませんでした。
