### ISSUE TITLE
Grid::assign による不具合

### ISSUE THREAD

**Issue by NachiaVivias** [Siv3D/OpenSiv3D#995]
**予期しない動作の内容 | Describe the unexpected behavior**

Grid に対して現在のサイズと異なるサイズで assign すると、サイズと内部のレイアウトが一致しなくなり、その後の一部の操作で実行時エラーになる。

**再現方法 | To Reproduce**

```c++
# include <Siv3D.hpp> // OpenSiv3D v0.6.8
void Main() {
	Grid<int> A(Size(5, 5));
	A.assign(Size(2, 2), -1);
	Console << A.size(); // (5, 5)
	Console << A;        // out of range <- ???
}
```

**備考 | Additional context**

vector::assign や Array::assign は配列のサイズを変更する（というかコンテナを再構築している）一方で Grid::assign が自身のサイズを更新していないため。

cf. Grid.ipp https://github.com/Siv3D/OpenSiv3D/blob/c561cba1d88eb9cd9606ba983fcc1120192d5615/Siv3D/include/Siv3D/detail/Grid.ipp#L128-L140

[cppreference.com の vector::assign の項](https://en.cppreference.com/w/cpp/container/vector/assign)

**Comment by Reputeless** [comment]
Fixed. Good catch!
